In [1]:
library(tidyverse)
library(BiocParallel)
library(parallel)
library(sva)

# Custom package
library(rutils)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ─────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.7
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   2.0.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Loading required package: mgcv

Loading required package: nlme


Attaching package: ‘nlme’


The following object is masked from ‘package:dplyr’:

    collapse


This is mgcv 1.8-36. For overview type 'help("mgcv-package")'.

Loading required package: genefilter


Attaching package: ‘genefilter’


The following object is masked from ‘package:readr’:

    spec

In [2]:
n_cores <- detectCores() - 2
# Might be different depening on OS
mc_param <- SnowParam(n_cores)

# Load data

In [3]:
dsets <- c("GSE4888", "GSE6364", "GSE7305", "GSE51981")
batches <- as.list(setNames(seq(1, length(dsets)), dsets))

dirs <- rutils::get_dev_directories("../dev_paths.txt")
lnames <- load("../proj/proj_vals.Rdata")

In [4]:
matrisome_df <- rutils::load_matrisome_df(paste0(dirs$data_dir, "/matrisome/matrisome_hs_masterlist.tsv")) %>%
    select(gene_symbol, division, category)
rma_dfs <- list()
clinical_dfs <- list()

for (ds in dsets) {
    rma_dfs[[ds]] <- read_tsv(paste0(dirs$data_dir, "/preprocessed_GEO_data/", ds, ".tsv"))
    clinical_dfs[[ds]] <- read_tsv(paste0(dirs$data_dir, "/preprocessed_GEO_clinical_data/", ds, ".tsv"))
}

# Handle making data uniform
clinical_dfs$GSE4888 <- clinical_dfs$GSE4888 %>%
    filter(condition == "normal") %>%
    rename(sample_name = geo_accession)
rma_dfs$GSE4888 <- rma_dfs$GSE4888 %>%
    select(one_of(c("symbol", clinical_dfs$GSE4888$sample_name)))

clinical_dfs$GSE6364 <- clinical_dfs$GSE6364 %>%
    rename(sample_name = geo_accession)

clinical_dfs$GSE51981 <- clinical_dfs$GSE51981 %>%
    filter(!(tissue == "unknown" | phase == "ambiguous_unknown" | condition == "unspecified_pathology")) %>%
    mutate(title = as.character(title)) %>%
    rename(sample_name = geo_accession)
rma_dfs$GSE51981 <- rma_dfs$GSE51981 %>%
    select(one_of(c("symbol", clinical_dfs$GSE51981$sample_name)))

all_clinical_df <- bind_rows(clinical_dfs$GSE4888, clinical_dfs$GSE6364, clinical_dfs$GSE51981) %>%
    rowwise() %>%
    mutate(batch = as.double(batches[[series]])) %>%
    ungroup() %>%
    mutate(
        condition = factor(condition, levels = c("normal", "endometriosis")),
        phase = factor(phase, levels = c("proliferative", "secretory_early", "secretory_mid", "secretory_late"))
    )

Rows: 1068 Columns: 11

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (9): Division, Category, Gene Symbol, Gene Name, Synonyms, UniProt_IDs, ...
dbl (2): HGNC_IDs, HGNC_IDs Links


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 21407 Columns: 28

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): symbol
dbl (27): GSM109814, GSM109815, GSM109816, GSM109817, GSM109818, GSM109819, ...


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 27 Columns: 7

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (7): geo_accession, series, title, condition, endometriosis_stage, phase...


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 21407 Columns: 38

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): symbol
dbl (37): GSM150190, GSM150191, GSM150192, GSM150193, GSM150194, GSM150195, ...


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 37 Columns: 7

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (7): geo_accession, series, title, condition, endometriosis_stage, phase...


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 21407 Columns: 21

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): symbol
dbl (20): GSM175766, GSM175767, GSM175768, GSM175769, GSM175770, GSM175771, ...


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 20 Columns: 7

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (7): geo_accession, series, title, condition, endometriosis_stage, phase...


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 21407 Columns: 149

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr   (1): symbol
dbl (148): GSM1256653, GSM1256654, GSM1256655, GSM1256656, GSM1256657, GSM12...


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 148 Columns: 7

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (6): geo_accession, series, condition, endometriosis_stage, phase, tissue
dbl (1): title


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [5]:
# Only need the "symbol" column from the first matrix (since all have same genes)
all_rma_df <- bind_cols(rma_dfs$GSE4888, rma_dfs$GSE6364[-1], rma_dfs$GSE51981[-1])

In [6]:
all_rma_df

      symbol     GSM109815 GSM109816 GSM109817 GSM109828 GSM109829 GSM109830
1     A1BG        5.685566  6.309144  6.558803  5.676761  5.713494  5.651049
2     A1BG-AS1    6.354643  7.025457  7.019929  6.820971  6.986295  7.019873
3     A1CF        6.017202  6.806242  5.876322  6.075240  6.048896  6.123009
4     A2M        10.705147 10.982733 11.381476 11.434625 11.319421 11.669190
5     A2M-AS1     6.193356  6.496668  6.377511  6.072465  5.664001  6.158695
6     A2ML1       5.936272  6.090145  5.661428  5.772800  5.649532  5.542943
7     A2MP1       6.193356  6.532157  5.972719  6.051718  6.131620  6.140529
8     A4GALT      7.399494  7.314846  7.260542  6.702430  7.204924  7.250284
9     A4GNT       6.212988  6.594580  6.254428  6.024918  6.118253  6.123767
10    AA06        5.930863  6.421702  5.644567  5.882695  5.635277  5.650887
11    AAAS        8.307991  8.295803  8.388261  8.010112  8.259921  8.205769
12    AACS        8.109643  8.180358  8.348733  8.734257  8.251885  8.558062
13    AACSP1      3.929684  3.895525  3.964031  3.969474  3.964031  3.966663
14    AADAC       5.236366  5.101236  4.890368  4.884971  5.055932  5.010302
15    AADACL2     3.546353  3.446094  3.429159  3.345847  3.335029  3.329403
16    AADACP1     4.195329  4.233906  4.064708  4.146682  4.332637  4.102171
17    AADAT       8.217651  8.030530  8.061634  7.286179  7.028966  7.569550
18    AAGAB       7.606111  7.503223  8.174740  7.783256  7.460035  7.370318
19    AAK1        8.192892  8.161748  8.759606  9.014288  8.558367  8.440802
20    AAMDC       8.055014  8.116838  8.075008  8.074759  8.066219  7.775633
21    AAMP        8.419181  8.594788  8.573453  8.750085  8.606666  8.527046
22    AANAT       5.177827  5.322801  5.369359  5.098724  4.951757  5.302356
23    AAR2        8.421017  8.401658  8.493604  8.282975  8.303842  8.343030
24    AARS1       9.543901  9.591302  9.893307  9.157779  9.311054  9.447131
25    AARS2       8.067759  8.034381  8.415032  7.888777  7.987126  7.998226
26    AARSD1      7.482547  7.608351  7.940040  7.518850  7.384443  7.532485
27    AASDH       8.052371  7.739719  7.874676  7.876890  8.106847  8.057399
28    AASDHPPT    9.067446  8.290863  8.518945  9.483085  9.170796  9.062673
29    AASS        5.677549  5.341292  6.071552  6.618679  6.546347  6.883874
30    AATBC       5.467827  5.544332  6.018107  5.124621  5.152694  5.087959
...   ...        ...       ...       ...       ...       ...       ...
21378 ZSCAN26     7.109178  7.076123  7.051512 6.917225   6.514280  6.893605
21379 ZSCAN29     8.216884  7.992500  8.218323 7.802147   7.951540  7.908428
21380 ZSCAN30     8.514174  8.299628  8.170274 8.131456   8.131456  8.089939
21381 ZSCAN31     6.752059  6.447047  6.928313 6.459476   6.427812  6.097731
21382 ZSCAN32     7.677679  7.673058  7.784663 7.648936   7.910495  7.659687
21383 ZSCAN4      5.035509  5.386720  5.037968 4.605544   4.948800  4.896786
21384 ZSCAN5A     5.472202  5.634845  5.873945 5.953466   5.637112  5.560187
21385 ZSCAN9      7.350241  7.180837  7.245642 7.204614   6.994458  7.118120
21386 ZSWIM1      8.202666  8.505625  8.315825 7.974520   7.957436  8.010033
21387 ZSWIM2      3.361498  3.470143  3.548872 3.553998   3.595670  3.445531
21388 ZSWIM3      6.995121  7.495298  7.248044 7.305173   7.116102  7.576682
21389 ZSWIM4      5.525347  5.663543  5.849868 5.199543   5.356806  5.385719
21390 ZSWIM5      6.948925  7.157071  6.963998 6.948925   6.518732  6.656286
21391 ZSWIM6      8.675910  8.588874  8.327364 8.616429   8.437852  8.598143
21392 ZSWIM7      7.759888  7.632400  8.194322 8.574203   8.194539  8.037877
21393 ZSWIM8      9.126002  9.309486  9.507074 9.570115   9.741320  9.607812
21394 ZSWIM8-AS1  7.458065  7.171647  7.106537 7.059145   6.886157  7.038252
21395 ZSWIM9      6.947680  7.083826  7.648701 7.099303   7.497107  7.403204
21396 ZUP1        6.102859  5.964587  6.253542 6.544367   6.542223  6.197361
21397 ZW10        8.313397  7.865162  8.008453 7.957020   8.083095  7.974213
21398 ZWILCH      8.648811  8.088589  9.103367 7.859225   7.721375  7.645658
21399 ZWINT       9.881066  9.122915 10.122005 7.821796   7.842639  7.414592
21400 ZXDA        5.569230  5.623114  5.564317 5.594251   5.624766  5.574619
21401 ZXDB        6.057409  5.680178  5.671394 6.156656   6.134825  6.298885
21402 ZXDC        7.272264  7.477129  7.342225 7.763413   7.754471  7.771071
21403 ZYG11A      5.896223  5.963051  5.816302 5.816189   6.331827  5.990648
21404 ZYG11B      7.953928  7.819311  8.357682 8.419856   7.860623  7.962587
21405 ZYX        10.110586 10.359008 10.440895 9.986121  10.122976 10.791009
21406 ZZEF1       7.695005  7.715166  7.836197 8.193168   8.122933  8.089190
21407 ZZZ3        8.311897  7.564208  8.048883 8.776825   7.966984  8.217494
      GSM109831 GSM150190 GSM150191 ... GSM1256786 GSM1256787 GSM1256788
1      6.095096  5.854344  5.447841 ...  6.145047   6.126593   6.599092
2      6.614798  6.777897  7.479844 ...  5.856890   5.941728   5.879944
3      6.480756  6.264393  6.434380 ...  5.837212   5.564375   5.263638
4     11.679939 10.869828 10.388754 ... 10.761609  10.889744  11.732717
5      5.950787  6.412899  5.860931 ...  6.304126   6.635071   7.063681
6      6.006635  5.731372  6.354088 ...  4.545159   4.468034   4.856192
7      6.239424  6.152233  6.558805 ...  5.449048   5.649246   5.601276
8      7.084704  6.865608  7.216150 ...  6.635044   6.238798   5.937796
9      6.236670  6.122098  6.744604 ...  5.807315   5.734504   5.434892
10     6.069808  5.626678  6.203526 ...  4.844510   5.082622   4.957434
11     8.234084  8.082291  8.147178 ...  8.096493   8.238614   7.992328
12     8.491659  8.300727  7.714807 ...  8.331215   8.516602   8.177435
13     3.788244  3.945245  4.361322 ...  3.525406   3.486968   3.351743
14     4.967961  5.111316  5.411072 ...  4.992655   4.844655   4.589229
15     3.333414  3.496602  3.757482 ...  3.439754   3.428175   3.298513
16     4.014776  4.094126  4.606717 ...  4.197613   5.706764   3.798727
17     7.404541  7.729568  7.848703 ...  7.670831   8.073664   7.255068
18     7.430850  7.739155  7.596560 ...  7.710256   8.055248   7.846377
19     8.546727  8.618612  7.628399 ...  9.039944   8.855634   9.467326
20     7.668705  8.041843  7.796556 ...  7.945993   8.155866   7.512504
21     8.770652  8.435820  8.120504 ...  9.212511   9.459621   8.962314
22     5.328901  4.567478  4.718607 ...  3.539596   3.560878   3.501282
23     8.488098  8.277176  8.254839 ...  8.324794   8.662160   8.397009
24     9.384313  9.563156  9.234248 ...  8.998826   9.343166   9.200696
25     7.960252  8.024087  8.000202 ...  7.997467   8.600154   7.779059
26     7.587459  7.501147  7.184270 ...  8.025407   7.964773   7.509383
27     7.765911  7.831731  7.662972 ...  9.050318   8.282933   8.465417
28     9.217809  8.878725  7.883812 ...  9.861369   9.624504   9.640918
29     6.527621  5.561070  6.100550 ...  6.744296   6.966357   7.221314
30     5.179004  4.860971  4.961115 ...  5.263320   4.447963   5.064625
...   ...       ...       ...           ...        ...        ...
21378  7.154439  7.372793 7.552123  ...  7.702541   7.866956   7.597471
21379  7.629679  8.000446 7.585797  ...  7.563803   7.865366   7.654287
21380  8.139856  8.347371 8.116229  ...  8.287626   8.310418   8.111198
21381  6.703945  6.802456 6.658085  ...  7.500702   6.038835   6.990836
21382  7.842288  7.558779 7.379085  ...  7.161805   7.839326   7.555062
21383  5.263727  4.716953 5.091194  ...  3.300124   3.422701   3.654867
21384  6.087788  5.830597 6.366768  ...  5.707048   5.637613   5.713837
21385  7.106800  7.459297 7.364988  ...  7.735860   7.848809   8.079883
21386  8.246556  8.023337 8.591141  ...  7.937853   7.632898   7.718239
21387  3.476423  3.571234 3.636870  ...  3.110070   3.268447   3.225183
21388  7.135233  7.078469 7.378123  ...  6.472033   6.638828   6.743903
21389  5.567231  5.726466 6.763118  ...  4.844428   4.752486   4.528204
21390  6.948925  6.811863 7.325368  ...  6.747098   6.470349   7.409743
21391  8.523862  8.759289 7.957918  ...  9.521089   9.529280  10.029878
21392  8.278743  8.104072 7.358606  ...  9.616418   9.234285   8.769148
21393  9.584670  9.170055 8.959530  ...  9.017184   9.643740   9.592139
21394  7.374351  7.418692 7.843204  ...  6.905493   6.869520   7.074293
21395  6.988004  7.222576 7.449571  ...  6.464938   6.416591   6.106336
21396  6.309947  6.810766 5.860931  ...  7.430857   7.547996   7.232903
21397  8.052676  8.053300 8.152276  ...  8.389121   8.402610   8.226992
21398  7.652648  9.021603 7.959196  ...  9.242705   9.471598   8.671624
21399  7.468962 10.073488 8.277640  ... 10.024236  10.803527   8.577224
21400  5.579764  5.742879 6.017361  ...  6.838841   7.468479   7.083488
21401  5.838733  6.120270 5.119027  ...  6.579078   6.945289   6.595507
21402  7.508499  7.298124 7.121228  ...  8.110356   8.092295   8.250386
21403  5.990648  6.074999 6.261449  ...  5.612637   5.502864   5.526059
21404  8.031315  9.066713 8.139196  ...  9.886741   9.822834   9.822953
21405 10.945596  9.980630 9.653893  ...  9.311806   9.544917  10.311554
21406  8.007628  7.730327 7.273386  ...  7.725579   8.376629   7.987984
21407  8.219092  8.411215 7.575345  ...  8.809289   8.617141   8.576812
      GSM1256791 GSM1256793 GSM1256796 GSM1256797 GSM1256798 GSM1256799
1      5.970239   6.057815   6.441339   5.991864   6.485949   6.274268
2      6.097081   5.844443   5.913063   6.025716   5.814924   5.692197
3      5.859302   5.610516   5.896221   5.446063   5.874074   5.643722
4     11.766133  11.044853  11.807358  11.383761  10.991057  11.188148
5      5.283829   6.359341   6.337862   6.054985   6.940392   6.448001
6      4.792261   4.448566   4.545780   4.483322   4.300889   4.633475
7      5.735641   5.779447   5.851594   5.304028   5.725718   5.835786
8      6.593342   6.728298   6.532459   6.351160   6.270813   6.634007
9      5.637010   5.550587   5.607756   5.769874   5.554944   5.787562
10     5.066143   4.871466   4.925577   4.943628   4.911822   5.000223
11     7.982244   8.017905   8.128601   8.086465   8.198445   7.749312
12     8.693597   8.466951   8.648765   8.576866   8.368719   8.352501
13     3.578936   3.569782   3.513709   3.453610   3.421158   3.398769
14     4.585067   4.942201   4.832751   4.538584   4.601221   4.825179
15     3.320431   3.547695   3.395487   3.298201   3.443312   3.375512
16     3.890721   4.225047   4.331935   3.532925   4.519945   4.995962
17     6.244108   7.446047   7.554998   6.660364   7.432924   7.563226
18     7.537615   8.012888   8.086671   7.358298   7.993465   8.105683
19     8.929340   8.916170   8.821425   9.133586   9.268756   8.992258
20     7.363037   7.851519   7.901537   7.201870   7.752115   7.603524
21     9.280645   9.109971   9.355301   9.341768   9.169748   8.967968
22     3.850096   3.459150   3.817479   3.585482   3.747887   3.600558
23     8.597843   8.523921   8.487898   8.527318   8.491412   8.358336
24     8.857425   9.524736   9.456844   9.081110   9.389380   9.269002
25     7.148617   7.794381   7.711646   7.425565   7.712290   7.678751
26     7.643028   7.925346   7.895422   7.390499   7.872309   7.906893
27     8.344577   8.658737   8.437049   8.358169   8.530377   8.352990
28    10.016798   9.648641   9.637565   9.580674   9.845261   9.822715
29     8.157372   6.252271   6.244295   7.798319   6.375154   6.119021
30     4.638745   5.138131   4.837437   5.229850   5.193096   4.859157
...   ...        ...        ...        ...        ...        ...
21378 6.856959    7.324594  7.673375    7.204686   7.569600   7.468294
21379 7.059508    7.685855  7.913707    7.413854   7.693825   7.706216
21380 7.269835    8.112582  7.942942    7.846023   7.986259   7.630738
21381 6.295584    7.545358  6.706842    6.284364   7.206398   7.325331
21382 6.908101    7.292972  7.536225    7.195680   7.239679   7.253883
21383 3.576419    3.514055  3.495686    3.485310   3.562228   3.615580
21384 5.745539    5.740749  5.671107    5.903136   5.854549   5.821910
21385 7.868716    7.931439  7.882521    7.727654   7.892062   7.546086
21386 7.944522    7.718188  7.657124    7.909772   7.869157   7.769023
21387 3.499231    3.326071  3.368869    3.377742   3.354900   3.422930
21388 7.591606    6.423671  6.587182    7.227096   6.573320   6.376345
21389 4.163487    4.508258  4.144247    4.539941   4.216087   4.281883
21390 6.418976    6.675792  6.517222    6.696021   6.964846   6.597050
21391 9.595528    9.697718  9.600063    9.213705   9.740356   9.933037
21392 8.693614    9.748254  9.239817    8.360510   9.383570   9.586812
21393 9.042768    9.025516  9.113190    9.761852   9.096625   9.202155
21394 6.819901    7.009118  7.038148    6.695819   7.173693   7.175808
21395 6.175177    6.248512  6.148899    6.176355   6.157981   6.265432
21396 6.915103    7.541890  7.338633    7.180017   7.327623   7.262416
21397 8.318118    8.645292  8.397216    8.528379   8.298508   8.554629
21398 8.249992    9.459652  9.049346    8.334374   9.531649   9.363143
21399 8.279516   10.758363  9.810701    8.031609  10.588996  10.467894
21400 6.868651    6.995159  6.925168    6.817811   7.313864   7.047173
21401 6.521789    6.301341  6.571706    6.350530   6.537333   6.476557
21402 7.933693    7.904401  7.884474    8.361829   7.979887   8.301872
21403 5.627928    5.649342  5.659402    5.687976   5.824901   5.852536
21404 9.171426    9.875506  9.750880    9.275788   9.976561   9.818295
21405 9.975513    9.546261  9.724022   10.181796   9.525950   9.609497
21406 7.919230    7.738156  7.710661    8.463290   7.615212   7.653101
21407 8.334747    8.739443  8.623752    8.526270   8.709801   8.772564
      GSM1256800
1      6.409687
2      5.790890
3      5.432071
4     10.986126
5      5.843957
6      4.386206
7      5.564395
8      6.556477
9      5.690706
10     4.867125
11     8.044103
12     8.604126
13     3.405184
14     4.717286
15     3.349114
16     4.650781
17     7.851872
18     7.940013
19     9.221833
20     8.123738
21     9.218128
22     3.673777
23     8.400214
24     9.265016
25     7.849056
26     8.198002
27     8.539929
28     9.654484
29     6.214807
30     5.617180
...   ...
21378  7.395970
21379  7.801890
21380  7.777404
21381  7.206091
21382  7.336240
21383  3.544368
21384  5.735711
21385  7.866841
21386  7.894232
21387  3.183452
21388  6.353501
21389  4.658269
21390  6.414118
21391  9.752861
21392  9.318420
21393  9.223354
21394  7.108046
21395  5.944691
21396  7.332322
21397  8.596704
21398  9.310364
21399 10.381774
21400  7.058102
21401  6.592110
21402  8.053633
21403  5.589273
21404  9.687331
21405  9.614051
21406  7.903793
21407  8.517893

In [10]:
all_clinical_df

    sample_name series   title            condition     endometriosis_stage
1   GSM109815   GSE4888  endometrium M165 normal        none
2   GSM109816   GSE4888  endometrium M169 normal        none
3   GSM109817   GSE4888  endometrium M182 normal        none
4   GSM109828   GSE4888  endometrium G98A normal        none
5   GSM109829   GSE4888  endometrium M153 normal        none
6   GSM109830   GSE4888  endometrium M158 normal        none
7   GSM109831   GSE4888  endometrium M163 normal        none
8   GSM150190   GSE6364  PE_D_26A         endometriosis moderate_severe
9   GSM150191   GSE6364  PE_D_508         endometriosis moderate_severe
10  GSM150192   GSE6364  PE_D_587         endometriosis moderate_severe
11  GSM150193   GSE6364  PE_D_594         endometriosis moderate_severe
12  GSM150194   GSE6364  PE_D_647         endometriosis moderate_severe
13  GSM150195   GSE6364  PE_D_651         endometriosis moderate_severe
14  GSM150196   GSE6364  PE_N_562         normal        none
15  GSM150197   GSE6364  PE_N_598         normal        none
16  GSM150198   GSE6364  PE_N_M165        normal        none
17  GSM150199   GSE6364  PE_N_M169        normal        none
18  GSM150201   GSE6364  PE_N_M182        normal        none
19  GSM150202   GSE6364  ESE_D_27A        endometriosis moderate_severe
20  GSM150203   GSE6364  ESE_D_489        endometriosis moderate_severe
21  GSM150204   GSE6364  ESE_D_496        endometriosis moderate_severe
22  GSM150205   GSE6364  ESE_D_517        endometriosis moderate_severe
23  GSM150206   GSE6364  ESE_D_575        endometriosis moderate_severe
24  GSM150207   GSE6364  ESE_D_599        endometriosis moderate_severe
25  GSM150208   GSE6364  ESE_N_629        normal        none
26  GSM150209   GSE6364  ESE_N_650        normal        none
27  GSM150210   GSE6364  ESE_N_664        normal        none
28  GSM150211   GSE6364  MSE_D_33A        endometriosis moderate_severe
29  GSM150212   GSE6364  MSE_D_516        endometriosis moderate_severe
30  GSM150213   GSE6364  MSE_D_540        endometriosis moderate_severe
... ...         ...      ...              ...           ...
124 GSM1256732  GSE51981 28               normal        none
125 GSM1256733  GSE51981 7                normal        none
126 GSM1256734  GSE51981 8                normal        none
127 GSM1256766  GSE51981 29               normal        none
128 GSM1256767  GSE51981 30               normal        none
129 GSM1256768  GSE51981 31               normal        none
130 GSM1256769  GSE51981 32               normal        none
131 GSM1256770  GSE51981 9                normal        none
132 GSM1256771  GSE51981 10               normal        none
133 GSM1256772  GSE51981 11               normal        none
134 GSM1256774  GSE51981 86               endometriosis minimal_mild
135 GSM1256776  GSE51981 87               endometriosis minimal_mild
136 GSM1256777  GSE51981 116              endometriosis moderate_severe
137 GSM1256778  GSE51981 84               endometriosis minimal_mild
138 GSM1256779  GSE51981 101              endometriosis moderate_severe
139 GSM1256780  GSE51981 146              endometriosis moderate_severe
140 GSM1256781  GSE51981 147              endometriosis moderate_severe
141 GSM1256782  GSE51981 117              endometriosis moderate_severe
142 GSM1256784  GSE51981 12               normal        none
143 GSM1256785  GSE51981 13               normal        none
144 GSM1256786  GSE51981 14               normal        none
145 GSM1256787  GSE51981 26               normal        none
146 GSM1256788  GSE51981 15               normal        none
147 GSM1256791  GSE51981 33               normal        none
148 GSM1256793  GSE51981 16               normal        none
149 GSM1256796  GSE51981 17               normal        none
150 GSM1256797  GSE51981 34               normal        none
151 GSM1256798  GSE51981 18               normal        none
152 GSM1256799  GSE51981 19               normal        none
153 GSM1256800  GSE51981 20               normal        none
    phase           tissue batch
1   proliferative   uterus 1
2   proliferative   uterus 1
3   proliferative   uterus 1
4   secretory_mid   uterus 1
5   secretory_mid   uterus 1
6   secretory_mid   uterus 1
7   secretory_mid   uterus 1
8   proliferative   uterus 2
9   proliferative   uterus 2
10  proliferative   uterus 2
11  proliferative   uterus 2
12  proliferative   uterus 2
13  proliferative   uterus 2
14  proliferative   uterus 2
15  proliferative   uterus 2
16  proliferative   uterus 2
17  proliferative   uterus 2
18  proliferative   uterus 2
19  secretory_early uterus 2
20  secretory_early uterus 2
21  secretory_early uterus 2
22  secretory_early uterus 2
23  secretory_early uterus 2
24  secretory_early uterus 2
25  secretory_early uterus 2
26  secretory_early uterus 2
27  secretory_early uterus 2
28  secretory_mid   uterus 2
29  secretory_mid   uterus 2
30  secretory_mid   uterus 2
... ...             ...    ...
124 secretory_mid   uterus 4
125 proliferative   uterus 4
126 proliferative   uterus 4
127 secretory_mid   uterus 4
128 secretory_mid   uterus 4
129 secretory_mid   uterus 4
130 secretory_mid   uterus 4
131 proliferative   uterus 4
132 proliferative   uterus 4
133 proliferative   uterus 4
134 secretory_early uterus 4
135 secretory_early uterus 4
136 proliferative   uterus 4
137 secretory_early uterus 4
138 proliferative   uterus 4
139 secretory_mid   uterus 4
140 secretory_mid   uterus 4
141 proliferative   uterus 4
142 proliferative   uterus 4
143 proliferative   uterus 4
144 proliferative   uterus 4
145 secretory_early uterus 4
146 proliferative   uterus 4
147 secretory_mid   uterus 4
148 proliferative   uterus 4
149 proliferative   uterus 4
150 secretory_mid   uterus 4
151 proliferative   uterus 4
152 proliferative   uterus 4
153 proliferative   uterus 4

In [15]:
all(colnames(all_rma_df)[-1] == all_clinical_df$sample_name)

[1] TRUE

# Prep data

In [16]:
rma_expr <- as.matrix(all_rma_df[-1])
rownames(rma_expr) <- all_rma_df$symbol
model_m <- model.matrix(~ condition, data = all_clinical_df)
batch <- all_clinical_df$batch

# Batch Correction

## Choose reference batch

In [20]:
ref_batch <- match("GSE4888", dsets)

In [21]:
ref_batch

[1] 1

## THE MAGIC

In [27]:
bc_rma_expr <- ComBat(rma_expr, batch = batch, mod = model_m, BPPARAM = mc_param, ref.batch = ref_batch)

Using batch =1as a reference batch (this batch won't change)

Found3batches

Adjusting for1covariate(s) or covariate level(s)

Standardizing Data across genes

Fitting L/S model and finding priors

Finding parametric adjustments

Adjusting the Data

In [28]:
bc_rma_expr_df <- bc_rma_expr %>%
    as_tibble(rownames = "symbol")

In [29]:
bc_rma_expr_df

      symbol     GSM109815 GSM109816 GSM109817 GSM109828 GSM109829 GSM109830
1     A1BG        5.685566  6.309144  6.558803  5.676761  5.713494  5.651049
2     A1BG-AS1    6.354643  7.025457  7.019929  6.820971  6.986295  7.019873
3     A1CF        6.017202  6.806242  5.876322  6.075240  6.048896  6.123009
4     A2M        10.705147 10.982733 11.381476 11.434625 11.319421 11.669190
5     A2M-AS1     6.193356  6.496668  6.377511  6.072465  5.664001  6.158695
6     A2ML1       5.936272  6.090145  5.661428  5.772800  5.649532  5.542943
7     A2MP1       6.193356  6.532157  5.972719  6.051718  6.131620  6.140529
8     A4GALT      7.399494  7.314846  7.260542  6.702430  7.204924  7.250284
9     A4GNT       6.212988  6.594580  6.254428  6.024918  6.118253  6.123767
10    AA06        5.930863  6.421702  5.644567  5.882695  5.635277  5.650887
11    AAAS        8.307991  8.295803  8.388261  8.010112  8.259921  8.205769
12    AACS        8.109643  8.180358  8.348733  8.734257  8.251885  8.558062
13    AACSP1      3.929684  3.895525  3.964031  3.969474  3.964031  3.966663
14    AADAC       5.236366  5.101236  4.890368  4.884971  5.055932  5.010302
15    AADACL2     3.546353  3.446094  3.429159  3.345847  3.335029  3.329403
16    AADACP1     4.195329  4.233906  4.064708  4.146682  4.332637  4.102171
17    AADAT       8.217651  8.030530  8.061634  7.286179  7.028966  7.569550
18    AAGAB       7.606111  7.503223  8.174740  7.783256  7.460035  7.370318
19    AAK1        8.192892  8.161748  8.759606  9.014288  8.558367  8.440802
20    AAMDC       8.055014  8.116838  8.075008  8.074759  8.066219  7.775633
21    AAMP        8.419181  8.594788  8.573453  8.750085  8.606666  8.527046
22    AANAT       5.177827  5.322801  5.369359  5.098724  4.951757  5.302356
23    AAR2        8.421017  8.401658  8.493604  8.282975  8.303842  8.343030
24    AARS1       9.543901  9.591302  9.893307  9.157779  9.311054  9.447131
25    AARS2       8.067759  8.034381  8.415032  7.888777  7.987126  7.998226
26    AARSD1      7.482547  7.608351  7.940040  7.518850  7.384443  7.532485
27    AASDH       8.052371  7.739719  7.874676  7.876890  8.106847  8.057399
28    AASDHPPT    9.067446  8.290863  8.518945  9.483085  9.170796  9.062673
29    AASS        5.677549  5.341292  6.071552  6.618679  6.546347  6.883874
30    AATBC       5.467827  5.544332  6.018107  5.124621  5.152694  5.087959
...   ...        ...       ...       ...       ...       ...       ...
21378 ZSCAN26     7.109178  7.076123  7.051512 6.917225   6.514280  6.893605
21379 ZSCAN29     8.216884  7.992500  8.218323 7.802147   7.951540  7.908428
21380 ZSCAN30     8.514174  8.299628  8.170274 8.131456   8.131456  8.089939
21381 ZSCAN31     6.752059  6.447047  6.928313 6.459476   6.427812  6.097731
21382 ZSCAN32     7.677679  7.673058  7.784663 7.648936   7.910495  7.659687
21383 ZSCAN4      5.035509  5.386720  5.037968 4.605544   4.948800  4.896786
21384 ZSCAN5A     5.472202  5.634845  5.873945 5.953466   5.637112  5.560187
21385 ZSCAN9      7.350241  7.180837  7.245642 7.204614   6.994458  7.118120
21386 ZSWIM1      8.202666  8.505625  8.315825 7.974520   7.957436  8.010033
21387 ZSWIM2      3.361498  3.470143  3.548872 3.553998   3.595670  3.445531
21388 ZSWIM3      6.995121  7.495298  7.248044 7.305173   7.116102  7.576682
21389 ZSWIM4      5.525347  5.663543  5.849868 5.199543   5.356806  5.385719
21390 ZSWIM5      6.948925  7.157071  6.963998 6.948925   6.518732  6.656286
21391 ZSWIM6      8.675910  8.588874  8.327364 8.616429   8.437852  8.598143
21392 ZSWIM7      7.759888  7.632400  8.194322 8.574203   8.194539  8.037877
21393 ZSWIM8      9.126002  9.309486  9.507074 9.570115   9.741320  9.607812
21394 ZSWIM8-AS1  7.458065  7.171647  7.106537 7.059145   6.886157  7.038252
21395 ZSWIM9      6.947680  7.083826  7.648701 7.099303   7.497107  7.403204
21396 ZUP1        6.102859  5.964587  6.253542 6.544367   6.542223  6.197361
21397 ZW10        8.313397  7.865162  8.008453 7.957020   8.083095  7.974213
21398 ZWILCH      8.648811  8.088589  9.103367 7.859225   7.721375  7.645658
21399 ZWINT       9.881066  9.122915 10.122005 7.821796   7.842639  7.414592
21400 ZXDA        5.569230  5.623114  5.564317 5.594251   5.624766  5.574619
21401 ZXDB        6.057409  5.680178  5.671394 6.156656   6.134825  6.298885
21402 ZXDC        7.272264  7.477129  7.342225 7.763413   7.754471  7.771071
21403 ZYG11A      5.896223  5.963051  5.816302 5.816189   6.331827  5.990648
21404 ZYG11B      7.953928  7.819311  8.357682 8.419856   7.860623  7.962587
21405 ZYX        10.110586 10.359008 10.440895 9.986121  10.122976 10.791009
21406 ZZEF1       7.695005  7.715166  7.836197 8.193168   8.122933  8.089190
21407 ZZZ3        8.311897  7.564208  8.048883 8.776825   7.966984  8.217494
      GSM109831 GSM150190 GSM150191 ... GSM1256786 GSM1256787 GSM1256788
1      6.095096  6.734897  6.311050 ...  5.807815   5.799219   6.019293
2      6.614798  7.162332  7.692469 ...  6.700733   6.763380   6.717756
3      6.480756  6.343271  6.492033 ...  6.245288   6.031817   5.796515
4     11.679939 11.021458 10.674658 ... 11.147112  11.202096  11.563820
5      5.950787  6.176829  5.792399 ...  6.171834   6.317519   6.506197
6      6.006635  5.752719  6.293694 ...  5.671488   5.636839   5.811221
7      6.239424  6.046551  6.383859 ...  6.038329   6.151578   6.124441
8      7.084704  7.514505  7.745656 ...  7.101046   6.920610   6.783544
9      6.236670  6.186598  6.752778 ...  6.290891   6.244271   6.052436
10     6.069808  6.140968  6.651462 ...  5.617088   5.788808   5.698525
11     8.234084  8.820366  8.841333 ...  8.229365   8.258646   8.207903
12     8.491659  8.466856  7.965819 ...  8.217413   8.320430   8.131960
13     3.788244  4.091420  4.259403 ...  3.954058   3.943550   3.906583
14     4.967961  4.943560  5.209078 ...  5.078745   5.009537   4.890094
15     3.333414  3.435472  3.597981 ...  3.415586   3.411070   3.360500
16     4.014776  3.706243  3.902163 ...  4.097777   4.336108   4.034784
17     7.404541  7.241694  7.323240 ...  7.940188   8.180325   7.692343
18     7.430850  7.523908  7.421382 ...  7.627439   7.798608   7.694976
19     8.546727  8.891466  8.038107 ...  8.660326   8.569440   8.871073
20     7.668705  8.089407  7.903707 ...  8.015142   8.095324   7.849528
21     8.770652  8.930768  8.803504 ...  8.588618   8.642460   8.534103
22     5.328901  5.282454  5.398886 ...  5.172102   5.182058   5.154178
23     8.488098  8.607663  8.597455 ...  8.275629   8.363550   8.294449
24     9.384313  9.645456  9.367470 ...  9.305289   9.532917   9.438737
25     7.960252  8.267566  8.259086 ...  8.073916   8.286057   7.997038
26     7.587459  7.482651  7.239977 ...  7.596378   7.567823   7.353357
27     7.765911  7.465083  7.396798 ...  8.139716   7.957985   8.001201
28     9.217809  8.334742  7.553641 ...  9.084696   8.973662   8.981356
29     6.527621  5.225151  5.784518 ...  6.429095   6.580245   6.753786
30     5.179004  5.399913  5.485502 ...  5.581113   5.067504   5.455951
...   ...       ...       ...           ...        ...        ...
21378  7.154439  6.689024  6.785045 ...  7.080316   7.134560   7.045651
21379  7.629679  7.624531  7.432917 ...  7.986879   8.067580   8.011093
21380  8.139856  8.262416  8.120504 ...  8.429097   8.437103   8.367128
21381  6.703945  6.504409  6.429966 ...  6.819994   6.281158   6.632060
21382  7.842288  7.320940  7.257361 ...  7.712568   7.866793   7.802085
21383  5.263727  5.002233  5.365453 ...  4.774163   4.884699   5.094060
21384  6.087788  5.702647  6.169688 ...  5.603089   5.565921   5.606723
21385  7.106800  6.872518  6.835312 ...  7.191438   7.219929   7.278219
21386  8.246556  8.474213  8.840692 ...  8.163252   8.050695   8.082194
21387  3.476423  3.585297  3.623366 ...  3.410362   3.470615   3.454156
21388  7.135233  7.155537  7.417448 ...  7.139732   7.237429   7.298975
21389  5.567231  5.806333  6.427823 ...  5.549182   5.508122   5.407960
21390  6.948925  6.897496  7.263412 ...  6.911552   6.760722   7.272697
21391  8.523862  7.971424  7.785754 ...  8.605190   8.606448   8.683372
21392  8.278743  8.147384  7.490883 ...  8.359025   8.182006   7.966536
21393  9.584670  9.793728  9.668450 ...  9.399047   9.682068   9.658759
21394  7.374351  7.202844  7.629388 ...  7.224682   7.197556   7.351966
21395  6.988004  7.671347  7.822888 ...  7.185195   7.159288   6.993037
21396  6.309947  5.765030  5.385109 ...  6.376304   6.407025   6.324388
21397  8.052676  7.728957  7.776226 ...  8.087542   8.092010   8.033841
21398  7.652648  8.141406  7.354612 ...  8.429574   8.564270   8.093513
21399  7.468962  9.559818  7.978119 ...  9.152311   9.818276   7.915724
21400  5.579764  5.168726  5.183906 ...  5.594935   5.622950   5.605820
21401  5.838733  5.897716  5.174408 ...  5.997602   6.164834   6.005104
21402  7.508499  7.522286  7.363451 ...  7.686328   7.674030   7.781673
21403  5.990648  5.985147  6.172638 ...  5.937042   5.867404   5.882119
21404  8.031315  8.291714  7.783332 ...  8.336214   8.311109   8.311155
21405 10.945596 11.130939 10.951452 ... 10.244438  10.337396  10.643108
21406  8.007628  7.800383  7.488816 ...  7.841115   8.161412   7.970211
21407  8.219092  8.060108  7.393353 ...  8.436745   8.311800   8.285576
      GSM1256791 GSM1256793 GSM1256796 GSM1256797 GSM1256798 GSM1256799
1      5.726396   5.767185   5.945817   5.736468   5.966595   5.868001
2      6.878098   6.691541   6.742213   6.825399   6.669743   6.579118
3      6.262572   6.067918   6.291459   5.939247   6.274130   6.093899
4     11.578159  11.268654  11.595849  11.414081  11.245570  11.330142
5      5.722692   6.196140   6.186685   6.062160   6.451924   6.235170
6      5.782499   5.628093   5.671767   5.643708   5.561749   5.711164
7      6.200450   6.225230   6.266043   5.956293   6.194836   6.257100
8      7.082056   7.143511   7.054332   6.971775   6.935188   7.100574
9      6.181848   6.126513   6.163117   6.266918   6.129302   6.278243
10     5.776924   5.636527   5.675551   5.688569   5.665631   5.729384
11     8.205826   8.213173   8.235980   8.227298   8.250370   8.157834
12     8.418783   8.292840   8.393871   8.353918   8.238254   8.229242
13     3.968692   3.966190   3.950861   3.934431   3.925559   3.919438
14     4.888148   5.055151   5.003970   4.866412   4.895702   5.000429
15     3.369048   3.457685   3.398321   3.360378   3.416974   3.390531
16     4.049312   4.102110   4.118990   3.992807   4.148681   4.223856
17     7.089688   7.806189   7.871137   7.337827   7.798366   7.876042
18     7.541782   7.777591   7.814199   7.452814   7.767954   7.823631
19     8.605785   8.599291   8.552571   8.706502   8.773155   8.636811
20     7.792424   7.979048   7.998158   7.730851   7.941071   7.884302
21     8.603463   8.566275   8.619730   8.616782   8.579300   8.535335
22     5.317361   5.134467   5.302102   5.193568   5.269546   5.200621
23     8.346789   8.327524   8.318136   8.328409   8.319051   8.284370
24     9.211815   9.652945   9.608065   9.359684   9.563467   9.483891
25     7.775128   8.002432   7.973310   7.872611   7.973536   7.961731
26     7.416297   7.549254   7.535162   7.297368   7.524277   7.540564
27     7.972583   8.046983   7.994483   7.975802   8.016584   7.974576
28     9.157556   8.984977   8.979785   8.953116   9.077145   9.066577
29     7.390930   6.094190   6.088761   7.146534   6.177832   6.003490
30     5.187682   5.502254   5.312841   5.560029   5.536877   5.326523
...   ...        ...        ...        ...        ...        ...
21378  6.801341   6.955624   7.070694   6.916064   7.036456   7.003033
21379  7.851925   8.019541   8.080516   7.946751   8.021674   8.024990
21380  8.071606   8.367614   8.308029   8.273988   8.323244   8.198370
21381  6.375794   6.836454   6.527382   6.371659   6.711515   6.755353
21382  7.654817   7.742425   7.797797   7.720279   7.730294   7.733528
21383  5.023318   4.967080   4.950515   4.941158   5.010521   5.058632
21384  5.623692   5.621128   5.583850   5.708052   5.682045   5.664573
21385  7.224951   7.240773   7.228434   7.189368   7.230840   7.143566
21386  8.165714   8.082175   8.059636   8.152887   8.137897   8.100938
21387  3.558416   3.492538   3.508820   3.512196   3.503506   3.529387
21388  7.795503   7.111404   7.207178   7.581998   7.199059   7.083684
21389  5.245082   5.399053   5.236490   5.413202   5.268573   5.297956
21390  6.732723   6.872689   6.786268   6.883714   7.030225   6.829774
21391  8.616628   8.632331   8.617325   8.557956   8.638883   8.668491
21392  7.931545   8.420097   8.184568   7.777238   8.251161   8.345311
21393  9.410604   9.402811   9.442414   9.735420   9.434932   9.482600
21394  7.160141   7.302821   7.324711   7.066575   7.426920   7.428514
21395  7.029925   7.069223   7.015844   7.030557   7.020711   7.078289
21396  6.241042   6.405423   6.352117   6.310518   6.349230   6.332128
21397  8.064024   8.172392   8.090223   8.133668   8.057529   8.142363
21398  7.845397   8.557240   8.315789   7.895053   8.599608   8.500448
21399  7.661309   9.779680   8.969828   7.449453   9.634942   9.531451
21400  5.596262   5.601890   5.598776   5.594000   5.616071   5.604205
21401  5.971441   5.870772   5.994235   5.893234   5.978539   5.950785
21402  7.566040   7.546095   7.532527   7.857553   7.597493   7.816729
21403  5.946743   5.960328   5.966710   5.984837   6.071701   6.089232
21404  8.055209   8.331800   8.282842   8.096207   8.371499   8.309326
21405 10.509105  10.337931  10.408817  10.591364  10.329832  10.363148
21406  7.936386   7.847303   7.833776   8.204047   7.786818   7.805458
21407  8.128172   8.391327   8.316099   8.252710   8.372052   8.412864
      GSM1256800
1      5.931074
2      6.651996
3      5.928299
4     11.243454
5      5.969264
6      5.600078
7      6.103579
8      7.065269
9      6.216228
10     5.633397
11     8.218571
12     8.369066
13     3.921192
14     4.949976
15     3.380235
16     4.169343
17     8.048110
18     7.741434
19     8.750017
20     8.083049
21     8.589842
22     5.234875
23     8.295284
24     9.481256
25     8.021677
26     7.677662
27     8.018847
28     8.987716
29     6.068689
30     5.804015
...   ...
21378  6.979172
21379  8.050593
21380  8.249886
21381  6.711402
21382  7.752275
21383  4.994415
21384  5.618431
21385  7.224478
21386  8.147152
21387  3.438279
21388  7.070303
21389  5.466046
21390  6.730076
21391  8.640805
21392  8.220981
21393  9.492176
21394  7.377418
21395  6.906418
21396  6.350462
21397  8.156299
21398  8.469389
21399  9.457855
21400  5.604691
21401  6.003553
21402  7.647706
21403  5.922221
21404  8.257878
21405 10.364964
21406  7.928791
21407  8.247264