In [9]:
library(tidyverse)
library(BiocParallel)
library(parallel)
library(sva)
library(dplyr)
library(ggplot2)
library(magrittr)

── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Loading required package: mgcv

Loading required package: nlme


Attaching package: ‘nlme’


The following object is masked from ‘package:dplyr’:

    collapse


This is mgcv 1.8-40. For overview type 'help("mgcv-package")'.

Loading required package: genefilter


Attaching package: ‘genefilter’


The following object is masked from ‘package:readr’:

    spec



Attaching package: ‘magrittr’


The following object is masked from ‘package:purrr’:

    set_names


The following object is masked from ‘package:tidyr’:

    extract

In [20]:
#command line arguments
args = commandArgs(trailingOnly = TRUE)

In [21]:
#command line arguments
#countspath = args[1]
countspath =  "example-data/rnaseq/counts_bc-in.tsv"
#coldatapath = args[2]
coldatapath = "example-data/rnaseq/coldata_bc-in.tsv"
#user_directory = args[3]

In [22]:
#importing the sample data and counts
counts <- readr::read_tsv(countspath)
metadata <- readr::read_tsv(coldatapath)

Rows: 20242 Columns: 11
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): Hugo_Symbol
dbl (10): GTEX-ZLWG-1026-SM-4WWC4, GTEX-13OVJ-2326-SM-5IJGA, GTEX-14BIM-2226...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 10 Columns: 3
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): sample_name, condition
dbl (1): batch

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [23]:
#creating correct data structures for batch correction
rma_expr <- as.matrix(counts[-1])
rownames(rma_expr) <- counts$Hugo_Symbol
model_m <- model.matrix(~ condition, data = metadata)
batch <- metadata$batch

In [24]:
#getting label for output
labels <- counts$Hugo_Symbol
label <- data.frame(labels)

In [15]:
rma_expr

              GTEX-ZLWG-1026-SM-4WWC4 GTEX-13OVJ-2326-SM-5IJGA
FAM208A       2715.29                 2192.72
RADIL          517.00                  914.00
AP1M2            4.00                    2.00
TAF1          2673.00                 3581.00
SIGLEC5          9.49                   18.69
KLF1             1.00                    7.00
USHBP1         334.00                  529.00
LRRC38           2.00                    0.00
NKPD1           10.00                    9.00
SLC26A8          8.00                    8.00
SGCA          1264.00                  479.00
PGF            642.00                  289.00
OR5H14           0.00                    0.00
KLHL1            0.00                    0.00
TUBA3C           1.09                   12.23
UFM1          2299.00                 5104.00
TNPO2         3618.00                 4702.00
NACA2            0.00                    5.00
TMEM256        417.73                  961.97
IFI35          672.00                  739.00
AP001362.1       0.00                    0.00
KLF16          336.12                  142.76
AC026703.1      56.06                   57.99
TCF21          466.45                  370.81
GNL2          1724.00                 2307.00
OR11G2           0.00                    0.00
SLC5A7          26.00                   17.00
OR5A2            0.00                    0.00
MTRNR2L1         0.00                    0.00
SORCS1          92.00                  214.00
⋮             ⋮                       ⋮
NDUFC2-KCTD14    17.02                    8.89
AC104794.4        0.00                    0.00
TEPP             55.00                  188.00
CD151         11295.50                12272.78
CCDC15           42.00                   46.00
PRKCA          1775.00                 1358.00
MAPKAPK3        789.00                  849.00
OXGR1            16.00                   13.00
ZGLP1            77.95                  102.70
ARSD           1118.62                  928.64
AC009403.2       42.00                   39.00
FAM117A        1127.03                  997.03
DUSP14          294.00                   65.00
SCO1            619.00                  549.00
NCOA5          2204.00                 1432.00
SIRT4            28.00                   21.00
CAPZB          6900.00                 9165.00
THEM4           551.00                  376.00
RAB11B         3522.42                 5144.97
C19orf77          6.00                    2.00
DAB2           1644.00                 3589.00
SLC35G1         175.00                  137.00
AL050303.1        0.00                    0.00
NCF2            207.00                  220.00
IFT52           953.00                  666.00
CNGA4            17.00                   15.00
SNRNP35         560.78                  690.47
ALOX12           16.00                    8.06
SNRNP48         676.00                 1340.00
C9orf171          0.00                    1.00
              GTEX-14BIM-2226-SM-5SI8Y GTEX-Q734-1626-SM-48U1B
FAM208A       3086.56                  2888.33
RADIL          884.00                   361.00
AP1M2            2.00                     6.00
TAF1          2568.00                  2741.00
SIGLEC5         11.83                    17.94
KLF1             1.00                     0.00
USHBP1         920.62                   924.00
LRRC38           2.00                     0.00
NKPD1            4.76                    22.40
SLC26A8         12.00                     4.00
SGCA           936.00                  1137.00
PGF            534.00                   252.00
OR5H14           0.00                     0.00
KLHL1            0.00                     0.00
TUBA3C           1.00                     2.00
UFM1          2983.00                  1572.00
TNPO2         3708.00                  3725.00
NACA2            6.00                     0.00
TMEM256        652.42                   539.62
IFI35          489.00                   553.00
AP001362.1      13.58                    18.68
KLF16          110.98                   463.54
AC026703.1     564.36                   282.34
TCF21          539.45                   362.80
GNL2          1348.00                  1085.00
OR11G2           0.00                     0.00
SLC5A7          39.00                    16.00
OR5A2            0.00                     0.00
MTRNR2L1         0.00                     0.00
SORCS1         141.00                   168.00
⋮             ⋮                        ⋮
NDUFC2-KCTD14   20.62                    17.45
AC104794.4       0.00                     0.00
TEPP           174.00                   185.00
CD151         8355.66                  9907.76
CCDC15          55.00                    40.00
PRKCA         1171.00                  2482.00
MAPKAPK3       765.32                   565.00
OXGR1           30.00                    20.00
ZGLP1          176.47                   278.06
ARSD           804.37                   683.83
AC009403.2      47.00                    56.00
FAM117A        979.05                  1831.00
DUSP14         200.00                   275.00
SCO1           521.00                   552.00
NCOA5         2280.00                  2901.00
SIRT4           99.00                   136.00
CAPZB         5719.00                  5066.00
THEM4          698.00                   571.00
RAB11B        2971.72                  4026.69
C19orf77         0.00                     2.00
DAB2          1698.00                  2922.00
SLC35G1        190.00                   102.00
AL050303.1       0.00                     0.00
NCF2           170.00                   157.00
IFT52         1035.00                   627.00
CNGA4            8.00                    13.00
SNRNP35        850.49                   787.08
ALOX12          14.00                    13.07
SNRNP48       1625.00                  1283.00
C9orf171         0.00                     1.00
              GTEX-S7SF-0826-SM-4AD4W GTEX-12WSD-2826-SM-59HKT
FAM208A       2074.97                 3125.08
RADIL          326.00                  708.00
AP1M2           19.00                    4.00
TAF1          1711.85                 3010.35
SIGLEC5         47.18                    3.90
KLF1             0.00                    0.00
USHBP1        1120.00                  730.00
LRRC38           3.00                    0.00
NKPD1            6.32                   10.00
SLC26A8          6.00                    6.00
SGCA           542.00                 1081.00
PGF            422.00                  226.00
OR5H14           2.00                    0.00
KLHL1            0.00                    0.00
TUBA3C           2.00                    2.00
UFM1          1596.00                 2792.00
TNPO2         2841.00                 4464.00
NACA2            5.00                    3.89
TMEM256        483.22                  389.87
IFI35          528.00                  759.00
AP001362.1       5.89                    0.00
KLF16          322.48                  247.14
AC026703.1     201.10                  284.25
TCF21          399.00                  764.43
GNL2           946.00                 1253.00
OR11G2           0.00                    0.00
SLC5A7          13.00                   50.00
OR5A2            0.00                    0.00
MTRNR2L1         0.00                    0.00
SORCS1         107.00                  129.00
⋮             ⋮                       ⋮
NDUFC2-KCTD14    0.00                    8.23
AC104794.4       0.00                    0.00
TEPP            10.00                  226.00
CD151         6356.17                 8779.90
CCDC15          27.00                   66.00
PRKCA         1360.00                 1418.00
MAPKAPK3       505.00                  661.35
OXGR1           27.00                   54.00
ZGLP1           92.78                  177.57
ARSD          1269.76                 1234.46
AC009403.2      29.00                   61.00
FAM117A       1204.04                 1625.97
DUSP14         136.00                  157.00
SCO1           501.00                  478.00
NCOA5         1287.00                 1397.00
SIRT4           49.00                   65.00
CAPZB         5983.00                 5805.00
THEM4          414.00                  685.00
RAB11B        3647.79                 4100.45
C19orf77         3.00                    2.00
DAB2          2637.00                 1624.00
SLC35G1        163.00                  133.00
AL050303.1       0.00                    1.00
NCF2           166.00                   64.00
IFT52          669.00                  992.00
CNGA4           16.00                   25.00
SNRNP35        560.33                  999.94
ALOX12          10.21                   27.22
SNRNP48        596.00                 1282.00
C9orf171         0.00                    0.00
              GTEX-145ME-1326-SM-5O98Q GTEX-S341-1026-SM-4AD71
FAM208A       2388.48                  1791.53
RADIL          235.00                   226.00
AP1M2            5.00                    23.00
TAF1          2272.00                  1632.98
SIGLEC5          9.26                     0.00
KLF1             2.00                     0.00
USHBP1         457.00                   705.00
LRRC38           0.00                    11.00
NKPD1           12.00                     6.00
SLC26A8          2.00                     4.00
SGCA          2106.00                  1430.00
PGF            309.00                   238.00
OR5H14           0.00                     0.00
KLHL1            0.00                     0.00
TUBA3C           1.07                     3.00
UFM1          2001.00                  1502.00
TNPO2         3812.00                  2398.00
NACA2            0.00                     3.00
TMEM256        369.91                   322.58
IFI35          470.00                   528.00
AP001362.1      34.61                     0.00
KLF16          422.39                   648.70
AC026703.1     112.20                   115.96
TCF21          375.57                   371.82
GNL2          1470.00                   930.00
OR11G2           0.00                     0.00
SLC5A7          11.00                     2.00
OR5A2            0.00                     0.00
MTRNR2L1         0.00                     0.00
SORCS1          42.00                    10.00
⋮             ⋮                        ⋮
NDUFC2-KCTD14    11.50                    16.97
AC104794.4        0.00                     0.00
TEPP              8.00                     8.00
CD151         13067.06                 13239.39
CCDC15           15.00                    15.00
PRKCA          2930.00                  2127.00
MAPKAPK3        373.00                   525.00
OXGR1            21.00                    36.00
ZGLP1            55.87                    36.87
ARSD            934.53                   799.00
AC009403.2       40.00                    36.00
FAM117A        1034.12                   977.01
DUSP14          342.00                   311.00
SCO1            597.00                   402.00
NCOA5          1514.00                  1120.00
SIRT4            66.00                    20.00
CAPZB          8692.00                  7246.00
THEM4           508.00                   471.00
RAB11B         3143.46                  2776.58
C19orf77          0.00                     4.00
DAB2           2897.00                  2199.00
SLC35G1         160.00                   175.00
AL050303.1        0.00                     0.00
NCF2             74.00                   153.00
IFT52           972.00                   721.00
CNGA4             3.00                     4.00
SNRNP35         607.50                   480.75
ALOX12           20.74                     7.09
SNRNP48         761.00                   446.00
C9orf171          0.00                     0.00
              GTEX-P4PP-2026-SM-3P61N GTEX-113JC-2226-SM-5EGJG
FAM208A       3661.58                 2231.58
RADIL         1614.00                  811.00
AP1M2           66.00                    3.00
TAF1          5170.20                 2064.30
SIGLEC5          6.37                    9.34
KLF1             0.00                    1.00
USHBP1         528.00                  205.00
LRRC38           2.00                    3.00
NKPD1           23.00                    7.12
SLC26A8          4.00                   17.00
SGCA            84.00                  341.00
PGF             61.00                  141.00
OR5H14           0.00                    0.00
KLHL1            0.00                    1.00
TUBA3C           0.00                    2.00
UFM1          4638.00                 2096.00
TNPO2         8606.14                 3371.00
NACA2            5.28                    0.00
TMEM256        689.36                  324.99
IFI35          701.00                  573.00
AP001362.1       0.00                    4.04
KLF16          318.80                  217.36
AC026703.1     218.76                   91.33
TCF21          101.00                 1034.00
GNL2          1631.00                  924.00
OR11G2           0.00                    0.00
SLC5A7           0.00                  214.00
OR5A2            0.00                    0.00
MTRNR2L1         0.00                    0.00
SORCS1        4321.05                  224.00
⋮             ⋮                       ⋮
NDUFC2-KCTD14   13.48                    6.12
AC104794.4       0.00                    0.00
TEPP           355.00                  150.00
CD151         7951.68                 7133.02
CCDC15         124.00                   55.00
PRKCA         6872.00                 1439.00
MAPKAPK3       971.00                  441.00
OXGR1           12.00                   20.00
ZGLP1          197.64                  101.31
ARSD          3005.35                  675.80
AC009403.2     114.00                   29.00
FAM117A       3268.98                 1123.08
DUSP14         268.00                  163.00
SCO1           741.00                  315.00
NCOA5         3128.00                 1057.00
SIRT4           96.00                   54.00
CAPZB         7772.00                 4842.00
THEM4         1181.00                  373.00
RAB11B        5485.59                 3403.75
C19orf77        11.00                    3.00
DAB2           706.00                 1276.00
SLC35G1        341.00                  135.00
AL050303.1       4.00                    0.00
NCF2            55.00                  100.00
IFT52         1601.00                  702.00
CNGA4           34.00                    8.00
SNRNP35        994.81                  595.49
ALOX12          73.35                   17.14
SNRNP48       1237.00                 1166.00
C9orf171         0.00                    1.00

In [25]:
labels

    [1] "FAM208A"            "RADIL"              "AP1M2"
    [4] "TAF1"               "SIGLEC5"            "KLF1"
    [7] "USHBP1"             "LRRC38"             "NKPD1"
   [10] "SLC26A8"            "SGCA"               "PGF"
   [13] "OR5H14"             "KLHL1"              "TUBA3C"
   [16] "UFM1"               "TNPO2"              "NACA2"
   [19] "TMEM256"            "IFI35"              "AP001362.1"
   [22] "KLF16"              "AC026703.1"         "TCF21"
   [25] "GNL2"               "OR11G2"             "SLC5A7"
   [28] "OR5A2"              "MTRNR2L1"           "SORCS1"
   [31] "NMS"                "ELAVL3"             "RAB11FIP4"
   [34] "UBR5"               "NOTCH2"             "LL22NC03-63E9.3"
   [37] "LAMTOR2"            "TIMP4"              "CASP16"
   [40] "8-Sep"              "GGT7"               "APEH"
   [43] "ASXL1"              "GNG10"              "GORASP1"
   [46] "SPERT"              "STAU1"              "KCNS1"
   [49] "YTHDC1"             "GNA12"              "AKR1E2"
   [52] "LDLR"               "RNF169"             "CFHR2"
   [55] "KRT9"               "ORMDL2"             "OR51B5"
   [58] "SPINT4"             "RAC1"               "CIZ1"
   [61] "LYST"               "SHISA9"             "B4GALT6"
   [64] "HSFY2"              "AUH"                "NT5DC1"
   [67] "AP001421.1"         "SERINC4"            "ATP13A2"
   [70] "CTRL"               "MALSU1"             "HRH4"
   [73] "P2RY11"             "INF2"               "NEDD4L"
   [76] "TBCE"               "TMLHE"              "NLRP1"
   [79] "ZMYND8"             "RP11-345J4.3"       "EIF5AL1"
   [82] "MCM10"              "SREBF2"             "RPP30"
   [85] "ACAD10"             "PITRM1"             "RP11-351M8.1"
   [88] "AC011308.1"         "SLC36A4"            "GEMIN5"
   [91] "SSC5D"              "NHLH2"              "RHBDL1"
   [94] "EIF2B2"             "TARDBP"             "EMC7"
   [97] "DDX58"              "C1QTNF6"            "C8orf59"
  [100] "NME3"               "TNC"                "NBPF20"
  [103] "CXorf40B"           "WDR82"              "MYO1E"
  [106] "STC2"               "POTEE"              "OR9A2"
  [109] "CDC23"              "SNX27"              "SLC6A3"
  [112] "GRAP2"              "TMC3"               "TOMM6"
  [115] "CCT5"               "RGS17"              "YKT6"
  [118] "RPL36A"             "AC017081.1"         "GGNBP2"
  [121] "NOL10"              "CTU2"               "BARX1"
  [124] "NELFCD"             "KBTBD3"             "USP30"
  [127] "NFAM1"              "ZNF850"             "SUSD2"
  [130] "UBE2U"              "ARL17B"             "KMO"
  [133] "ALX1"               "CORO7"              "OR11A1"
  [136] "CITED2"             "TP53TG3D"           "ARL5B"
  [139] "NEO1"               "ELF2"               "SDR42E1"
  [142] "NBPF4"              "KIF13B"             "NOTCH3"
  [145] "SF3A3"              "OLFM1"              "CETN2"
  [148] "CDH26"              "FBXO30"             "MIPOL1"
  [151] "OR5AK2"             "SLC48A1"            "FAM19A5"
  [154] "LY6K"               "OR2T10"             "TLR8"
  [157] "EIF5"               "AP2S1"              "MAGEL2"
  [160] "RP11-383H13.1"      "ATIC"               "C9orf147"
  [163] "RP11-178L8.4"       "REXO1L1"            "CEP68"
  [166] "ELMSAN1"            "IL10RA"             "EZH1"
  [169] "SHARPIN"            "PSG1"               "GTF2H3"
  [172] "AL353583.1"         "ITGB1"              "USF2"
  [175] "NECAB3"             "RP11-108K14.8"      "MXD3"
  [178] "RPF1"               "DYNLL1"             "SGOL2"
  [181] "PRL"                "WWC1"               "TPPP3"
  [184] "NTPCR"              "OGN"                "MTRR"
  [187] "C1QL3"              "SPG20OS"            "C19orf60"
  [190] "NUTM2E"             "PMCH"               "FGB"
  [193] "VCY"                "GPX2"               "TRIM52"
  [196] "FPGT-TNNI3K"        "CLDN16"             "DNAJB8"
  [199] "AC092384.1"         "PTGES3L-AARSD1"     "JAKMIP3"
  [202] "CLCN4"              "RP11-1084J3.4"      "CACNA2D1"
  [205] "ALPK2"              "FABP2"              "OR14I1"
  [208] "ZNF234"             "NNT"                "AC008948.1"
  [211] "SAAL1"              "IARS2"              "SRC"
  [214] "TMEM105"            "OR56A1"             "MYNN"
  [217] "GPER1"              "KRBA2"              "RNF183"
  [220] "STRN3"              "FLJ00418"           "GPR84"
  [223] "LRRC6"              "DNPH1"              "FAM134A"
  [226] "GHRH"               "C17orf51"           "COPG2"
  [229] "NDNF"               "RCC1"               "UBALD1"
  [232] "TMEM64"             "KCNE4"              "TMEM151B"
  [235] "SDR9C7"             "CCL22"              "RP11-761B3.1"
  [238] "ACTL6B"             "ABCA12"             "ZNF729"
  [241] "GPR112"             "MAP3K8"             "FAHD2B"
  [244] "GSTT2"              "ELSPBP1"            "THAP6"
  [247] "AFP"                "AL358333.1"         "PAEP"
  [250] "CASP9"              "CHRND"              "BICC1"
  [253] "MTCP1"              "CYR61"              "ECM1"
  [256] "PLA2G2A"            "NEIL3"              "RPL26L1"
  [259] "FSCN3"              "MED7"               "ANGPT2"
  [262] "SERPINF2"           "ATF6B"              "RARS"
  [265] "LSR"                "RP11-296A16.1"      "RPE"
  [268] "TYMS"               "C3orf79"            "ITPR2"
  [271] "RBM46"              "EFTUD2"             "TRIM39-RPP21"
  [274] "NMUR2"              "SLC22A11"           "PITPNB"
  [277] "PGAP2"              "NAPB"               "APOC1"
  [280] "GSTA2"              "SCUBE3"             "CRELD2"
  [283] "GOLIM4"             "NKTR"               "ZNF446"
  [286] "PAN2"               "KCNC2"              "PEAR1"
  [289] "SLC25A27"           "SLC6A12"            "SNX8"
  [292] "RAG2"               "DLC1"               "ERVMER34-1"
  [295] "YIPF1"              "RUFY2"              "DDX25"
  [298] "WFDC8"              "DCTN6"              "PPT2"
  [301] "SENP2"              "GBE1"               "KITLG"
  [304] "C7orf33"            "TCIRG1"             "KIF27"
  [307] "PMPCA"              "CDT1"               "GBA"
  [310] "CNTLN"              "KIAA0355"           "IAH1"
  [313] "THSD4"              "TCERG1"             "IPO11"
  [316] "GBA2"               "SRSF4"              "IDE"
  [319] "ZNF696"             "MORC3"              "PROKR1"
  [322] "KCNB1"              "NT5DC4"             "MEPE"
  [325] "MYLPF"              "USP17L30"           "TMEM236"
  [328] "PCCA"               "EDAR"               "USP2"
  [331] "SLC25A26"           "C5orf38"            "MSLN"
  [334] "FCRL2"              "ABCB1"              "ZSCAN2"
  [337] "CELA2B"             "MCF2"               "CLEC4G"
  [340] "ANGPTL7"            "FOXN2"              "CWF19L1"
  [343] "ZNF711"             "C11orf40"           "TLE1"
  [346] "SNX14"              "KIAA1462"           "SH2D6"
  [349] "SLK"                "IQSEC1"             "TFAP2E"
  [352] "QPRT"               "RP11-187E13.2"      "PKN3"
  [355] "AC013269.5"         "FBXL13"             "LHX6"
  [358] "EOGT"               "CCPG1"              "MTRNR2L13"
  [361] "MLNR"               "PCDHGA8"            "CLTC"
  [364] "ATAD1"              "TULP1"              "MIA2"
  [367] "C10orf25"           "EYA1"               "C22orf23"
  [370] "LYPD6B"             "PDGFRA"             "MS4A4A"
  [373] "C20orf26"           "RASGRF2"            "CCDC80"
  [376] "DCUN1D3"            "MRPL27"             "DDR2"
  [379] "RBBP6"              "QTRT1"              "UCK2"
  [382] "TNFRSF10D"          "TMBIM1"             "OR52E8"
  [385] "OR6B2"              "STRA13"             "HAX1"
  [388] "FBXO4"              "SPZ1"               "SRSF6"
  [391] "ZFPM2"              "C8orf82"            "AC019294.1"
  [394] "TRIM77"             "EFHB"               "STARD8"
  [397] "CCDC19"             "MYT1"               "CRBN"
  [400] "IL36B"              "AP000867.1"         "ZNF7"
  [403] "ASAH2B"             "NDUFV2"             "CDC123"
  [406] "TBCC"               "RFPL1"              "WBP11"
  [409] "PPP1R1B"            "FCRL4"              "CPQ"
  [412] "PSMD2"              "ZNF354A"            "LST3"
  [415] "LRRC40"             "TRIM13"             "PRSS46"
  [418] "TMC4"               "AP001350.1"         "ZNF490"
  [421] "FAM86B1"            "KIF12"              "ITGAX"
  [424] "FBF1"               "ZFP62"              "ZNF716"
  [427] "PALM"               "TDRD9"              "FAM169B"
  [430] "OPLAH"              "BTN3A3"             "OR5M1"
  [433] "TEX38"              "EFHC2"              "UBXN11"
  [436] "LCE2A"              "CARTPT"             "HOXC9"
  [439] "AC093323.1"         "RDH16"              "ARHGAP17"
  [442] "CCR1"               "NDUFAF2"            "ZNF708"
  [445] "NEUROD2"            "CSF3"               "GAGE12G"
  [448] "SOX18"              "DLEU2L"             "CHL1"
  [451] "RCN3"               "CFD"                "STARD7"
  [454] "TMEM199"            "SHANK3"             "SCAP"
  [457] "SLC9A6"             "ZNF280A"            "CYP11B1"
  [460] "HSPB9"              "FMO1"               "AK2"
  [463] "TRAK1"              "ZNF789"             "TPCN1"
  [466] "NT5C2"              "KRTAP8-1"           "PAOX"
  [469] "CTDSPL"             "RBM19"              "PHF19"
  [472] "FERMT3"             "CPOX"               "ZNF844"
  [475] "UTRN"               "RAB5B"              "TERF2"
  [478] "ALG5"               "ERAP2"              "ACO1"
  [481] "AC010646.3"         "GCGR"               "PCDHGA11"
  [484] "TMX3"               "ALG11"              "LRIG2"
  [487] "OR8B8"              "ALDOC"              "FOXD4L1"
  [490] "WHSC1L1"            "NDUFAF6"            "RBBP7"
  [493] "SSX7"               "AC018867.1"         "LOXL1"
  [496] "C16orf93"           "CCZ1B"              "AC104472.1"
  [499] "PCMT1"              "RTEL1"              "MICU3"
  [502] "ABCB5"              "PDXDC1"             "CLEC18A"
  [505] "KRTAP21-2"          "NOC4L"              "ATN1"
  [508] "KIAA2018"           "TMEM14E"            "CBX8"
  [511] "CC2D1A"             "FAM177B"            "IMMT"
  [514] "LYG2"               "ZBTB9"              "RPL36A-HNRNPH2"
  [517] "SOX6"               "LRTOMT"             "KCNJ15"
  [520] "AC106873.4"         "KCNJ14"             "CTAGE1"
  [523] "MDM4"               "FBXL17"             "HIF3A"
  [526] "TUBB4B"             "KCNH5"              "DUOX1"
  [529] "WDHD1"              "FAM136A"            "PHRF1"
  [532] "WDR24"              "GUCY2C"             "NDUFA7"
  [535] "MEF2BNB"            "SFR1"               "ABCG5"
  [538] "GNAT1"              "OR8S1"              "POLR3C"
  [541] "APPL2"              "DEFA6"              "METTL20"
  [544] "FAM13A"             "MOGS"               "CEA"
  [547] "DNHD1"              "EFCAB3"             "COX14"
  [550] "MUC3A"              "ALG14"              "AC131097.4"
  [553] "LIN52"              "AC073569.1"         "TCP1"
  [556] "SYNC"               "UGT1A1"             "CT47A2"
  [559] "SLC39A10"           "MBD6"               "C12orf79"
  [562] "AL645608.2"         "APOL4"              "ATF7IP"
  [565] "GPR132"             "SPANXN5"            "PXDNL"
  [568] "CORO7-PAM16"        "TENM2"              "CALHM3"
  [571] "DGKH"               "CYLC2"              "FGF9"
  [574] "SLAMF9"             "GAGE12D"            "SFTPD"
  [577] "PPARGC1B"           "ATRN"               "GJB1"
  [580] "FILIP1L"            "REEP3"              "RP11-210M15.2"
  [583] "PLEKHO2"            "ROR2"               "LINC00999"
  [586] "PRKCG"              "MTFP1"              "RABL6"
  [589] "C19orf59"           "GNL3L"              "SMAD3"
  [592] "B4GALNT2"           "SENP1"              "ADCY9"
  [595] "FSCB"               "RNF103"             "CT47A5"
  [598] "AC111200.1"         "MNT"                "CSRP3"
  [601] "MC2R"               "SMIM9"              "GSN"
  [604] "AADACL2"            "TMEM258"            "LONRF1"
  [607] "TBCCD1"             "LRP2"               "S100P"
  [610] "EDC3"               "CEP290"             "ATP6V0E1"
  [613] "JPH2"               "ACKR4"              "AC073610.5"
  [616] "SFRP1"              "CREBRF"             "SNX19"
  [619] "IFNL2"              "DCBLD2"             "ULBP2"
  [622] "DLK1"               "G6PC"               "LPIN2"
  [625] "PPP1R3A"            "HCRTR2"             "VPS33B"
  [628] "SPATA31A5"          "TMEM45B"            "PLA2R1"
  [631] "WTAP"               "PPP2R2A"            "BEAN1"
  [634] "NAA15"              "CDK13"              "MTL5"
  [637] "TMEM186"            "EMP3"               "MAPKBP1"
  [640] "LGALS2"             "PROX1"              "SNAPC5"
  [643] "FYTTD1"             "HBCBP"              "GSTT2B"
  [646] "MAP3K13"            "CCDC126"            "USP12"
  [649] "HOXA13"             "DPH6"               "CEP41"
  [652] "SERPINA4"           "GPR142"             "VWCE"
  [655] "TK2"                "SLC4A3"             "KNOP1"
  [658] "SMARCA1"            "PFN2"               "RHOB"
  [661] "DSPP"               "TNIP3"              "TSPYL4"
  [664] "GAPDHS"             "PAIP2"              "DEFB131"
  [667] "HTR5A"              "GGN"                "TTYH3"
  [670] "MRPL40"             "ANKRD16"            "CCDC108"
  [673] "METTL5"             "CCDC174"            "FAM3C"
  [676] "PRAMEF12"           "AC008686.1"         "LRRC52"
  [679] "RPS6KA4"            "TMEM120B"           "FAM105A"
  [682] "ZNF521"             "CTC-429P9.4"        "CSK"
  [685] "AIDA"               "GNB3"               "RP11-399J13.3"
  [688] "FITM1"              "CLU"                "RP11-389E17.1"
  [691] "EFNB1"              "CA5B"               "CRCT1"
  [694] "CCDC166"            "AC110619.2"         "PANK3"
  [697] "CLCA4"              "ZFAT"               "BLCAP"
  [700] "SLC17A9"            "RBM47"              "ATXN3L"
  [703] "HERPUD2"            "HBE1"               "NDUFB10"
  [706] "COL10A1"            "KCNK17"             "ACSS2"
  [709] "RNF152"             "ETV3L"              "GPR89B"
  [712] "PIGQ"               "WDR3"               "SPI1"
  [715] "GLOD5"              "GP5"                "GANAB"
  [718] "AKAP2"              "COX4I2"             "ZNF705B"
  [721] "ALG1"               "SELT"               "PYDC1"
  [724] "OR10S1"             "DDC8"               "SYAP1"
  [727] "RPA3"               "TUSC2"              "NDST2"
  [730] "TMEM217"            "PDPK1"              "GRXCR1"
  [733] "HOXA1"              "PPIL2"              "CREG2"
  [736] "HMSD"               "RP11-215A19.2"      "FIGN"
  [739] "TAGAP"              "ZSCAN18"            "ZBED5"
  [742] "FGG"                "ODF2L"              "VIMP"
  [745] "AC109829.1"         "FGF7"               "GALNT6"
  [748] "NAA40"              "TBPL1"              "GCH1"
  [751] "IL17RD"             "UBQLN1"             "ERLIN1"
  [754] "TCEANC"             "ETAA1"              "FAM217B"
  [757] "C18orf56"           "GLYR1"              "PDSS2"
  [760] "SSNA1"              "HOXB13"             "POLR3E"
  [763] "DHRSX"              "LOX"                "TPPP"
  [766] "UFC1"               "AC004076.7"         "FGF18"
  [769] "CLIC1"              "DCC"                "FLNA"
  [772] "RP11-298I3.5"       "AL645728.1"         "CYP21A2"
  [775] "DKFZP667F0711"      "WDFY1"              "SCARB2"
  [778] "MT2A"               "GNG5P2"             "PET112"
  [781] "GPR143"             "TNFRSF11A"          "RP11-432B6.3"
  [784] "ARPC2"              "MTERFD2"            "GATAD2A"
  [787] "TBC1D22A"           "DOCK1"              "SPTSSA"
  [790] "USP37"              "DNAJA2"             "DUS4L"
  [793] "LCAT"               "RAB33A"             "LIPA"
  [796] "UNC5B"              "DEFB135"            "SLC5A5"
  [799] "CD163"              "KDM5B"              "SULT1A4"
  [802] "RIMS3"              "C17orf112"          "RAB5A"
  [805] "GNB5"               "OR1K1"              "KLF2"
  [808] "RAB9B"              "EIF2S3L"            "CLDN22"
  [811] "AVEN"               "BAI3"               "LURAP1L"
  [814] "FAM186B"            "MDFIC"              "OBFC1"
  [817] "RMND1"              "HOXB8"              "SLC22A5"
  [820] "KRTAP19-6"          "PTH2"               "CD4"
  [823] "NIT2"               "DTX4"               "MTMR3"
  [826] "TTPAL"              "SRGAP1"             "C4orf47"
  [829] "ID3"                "DNAH3"              "TSR2"
  [832] "C12orf45"           "AC026202.1"         "GLIPR2"
  [835] "KM-PA-2"            "OR11H12"            "KLK14"
  [838] "TLR4"               "ACAT1"              "MED17"
  [841] "ACRC"               "DPP7"               "OR52W1"
  [844] "SGK223"             "CAPSL"              "C2orf57"
  [847] "DHFR"               "BLVRA"              "KIFAP3"
  [850] "CPSF1"              "DDHD2"              "GNAQ"
  [853] "RBM8A"              "CTRB2"              "DNAJC12"
  [856] "AC079354.1"         "C13orf35"           "C2orf16"
  [859] "OR5J2"              "HNRNPR"             "MAOA"
  [862] "TXNDC17"            "MCU"                "RASSF8"
  [865] "SLC24A3"            "ATP8B3"             "PARVG"
  [868] "QSOX2"              "MUC8"               "CNKSR3"
  [871] "FAM178B"            "OSCAR"              "CCDC115"
  [874] "PEX10"              "MYL6"               "PDGFD"
  [877] "JMJD6"              "PABPN1L"            "RP11-297M9.1"
  [880] "OTOR"               "STX2"               "ATXN7"
  [883] "TRIP4"              "COQ6"               "TBKBP1"
  [886] "CDC26"              "ZNF107"             "SYT14"
  [889] "MEI1"               "ZNF625"             "ATP5SL"
  [892] "DDOST"              "TM7SF2"             "TOX4"
  [895] "TACC2"              "RAVER1"             "RP11-332O19.5"
  [898] "IFNB1"              "OR11H6"             "S100PBP"
  [901] "RABGAP1L"           "RBM12B"             "TNFAIP2"
  [904] "GLT6D1"             "MAVS"               "STMN4"
  [907] "FERMT1"             "CCHCR1"             "CADM2"
  [910] "KLHDC4"             "RBBP9"              "SLAIN1"
  [913] "ISCA2"              "SYNPR"              "TMEM179"
  [916] "CUL9"               "RAB1B"              "STIL"
  [919] "CLIP2"              "AL445989.1"         "MRPL24"
  [922] "ARSI"               "STARD9"             "NUS1"
  [925] "RPTOR"              "FAM183B"            "KLHL38"
  [928] "IL36G"              "NINJ1"              "NEK2"
  [931] "LRRIQ3"             "PTGR2"              "HDAC9"
  [934] "MBTD1"              "MGAT1"              "JAKMIP2"
  [937] "AC091150.1"         "LRRTM2"             "SPATA18"
  [940] "LIMS2"              "ACAD9"              "EPM2AIP1"
  [943] "CHST10"             "ATP5I"              "TFEC"
  [946] "ELK3"               "ACTR5"              "ZNF286A"
  [949] "TMED10"             "HS3ST4"             "SCNN1A"
  [952] "ICT1"               "RP11-758M4.1"       "DEFA1B"
  [955] "PIP"                "CETN1"              "KLHL32"
  [958] "ARNTL2"             "KIF2B"              "C1orf226"
  [961] "GJC1"               "ISLR"               "POTEB2"
  [964] "PNOC"               "FKSG52"             "SBNO2"
  [967] "OR12D2"             "ANKRD13D"           "PRDM16"
  [970] "AGAP8"              "C5orf27"            "TMSB15A"
  [973] "DDO"                "KRTAP5-10"          "PTAFR"
  [976] "LHFPL3"             "RPS13"              "CSTA"
  [979] "RPRD1A"             "KMT2B"              "SLC5A1"
  [982] "VPS13D"             "SEPHS1"             "PAK4"
  [985] "GLB1L2"             "HOXA10"             "RP5-850E9.3"
  [988] "RNF148"             "IFNLR1"             "SLC10A1"
  [991] "RPL17"              "RGS3"               "PIWIL3"
  [994] "CLIC5"              "MNDA"               "FOXL2"
  [997] "LCE2B"              "C12orf57"           "TNFAIP8"
 [1000] "SAMD10"             "ACTR8"              "ZNF488"
 [1003] "C10orf113"          "FGD6"               "APOPT1"
 [1006] "PEX11B"             "DHDH"               "DPF3"
 [1009] "SPG21"              "RASGRP1"            "IL31RA"
 [1012] "MICALCL"            "KIF17"              "FAM122C"
 [1015] "BMPR1A"             "PNMAL1"             "ISX"
 [1018] "PAGE2"              "HOPX"               "ZNF34"

In [26]:
label

      labels
1     FAM208A
2     RADIL
3     AP1M2
4     TAF1
5     SIGLEC5
6     KLF1
7     USHBP1
8     LRRC38
9     NKPD1
10    SLC26A8
11    SGCA
12    PGF
13    OR5H14
14    KLHL1
15    TUBA3C
16    UFM1
17    TNPO2
18    NACA2
19    TMEM256
20    IFI35
21    AP001362.1
22    KLF16
23    AC026703.1
24    TCF21
25    GNL2
26    OR11G2
27    SLC5A7
28    OR5A2
29    MTRNR2L1
30    SORCS1
⋮     ⋮
20213 NDUFC2-KCTD14
20214 AC104794.4
20215 TEPP
20216 CD151
20217 CCDC15
20218 PRKCA
20219 MAPKAPK3
20220 OXGR1
20221 ZGLP1
20222 ARSD
20223 AC009403.2
20224 FAM117A
20225 DUSP14
20226 SCO1
20227 NCOA5
20228 SIRT4
20229 CAPZB
20230 THEM4
20231 RAB11B
20232 C19orf77
20233 DAB2
20234 SLC35G1
20235 AL050303.1
20236 NCF2
20237 IFT52
20238 CNGA4
20239 SNRNP35
20240 ALOX12
20241 SNRNP48
20242 C9orf171

In [27]:
model_m

   (Intercept) conditionhealthy
1  1           1
2  1           1
3  1           1
4  1           1
5  1           1
6  1           1
7  1           1
8  1           0
9  1           1
10 1           0

In [30]:
batch

 [1] 1 1 1 1 1 2 2 2 2 2

In [16]:
#batch correction!
#bc_rma_expr <- ComBat_seq(rma_expr, batch = batch, mod = model_m, ref.batch = 1)

bc_rma_expr <- ComBat_seq(rma_expr, batch = batch, group = NULL, covar_mod=model_m)

#bc_rma_expr <- ComBat_seq(rma_expr <- rma_expr[,colnames(rma_expr)!="Hugo_Symbol"], batch = batch)

Found 2 batches
Using null model in ComBat-seq.
Adjusting for 1 covariate(s) or covariate level(s)
Estimating dispersions
Fitting the GLM model
Shrinkage off - using GLM estimates for parameters
Adjusting the data

In [17]:
#editing and combining files
final <- data.frame(bc_rma_expr)
final2 <- bind_cols(label,final)

In [19]:
#writing out
write_tsv(final2,"bc_counts.tsv")