In [40]:
library(tidyverse)
library(BiocParallel)
library(parallel)
library(sva)
library(dplyr)
library(ggplot2)
library(magrittr)

In [41]:
#command line arguments
args = commandArgs(trailingOnly = TRUE)

In [50]:
#command line arguments for the python script
#countspath = args[1]
countspath =  "./rna_data/counts/rna_counts2.tsv"
#coldatapath = args[2]
coldatapath = "./rna_data/coldata/rna_coldata2.tsv"
#user_directory = args[3]
user_directory = ".rna_data/temp_user/"

In [51]:
#importing the sample data and counts
counts <- readr::read_tsv(countspath)
metadata <- readr::read_tsv(coldatapath)

Rows: 20242 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): Hugo_Symbol
dbl (11): Entrez_Gene_Id, GTEX-ZLWG-1026-SM-4WWC4, GTEX-13OVJ-2326-SM-5IJGA,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 10 Columns: 4
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (3): sample_name, condition, data_source
dbl (1): batch

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [52]:
#creating correct data structures for batch correction
entrez <- counts$Entrez_Gene_Id
#counts$Entrez_Gene_Id <- NULL


df = subset(counts, select = -c(Entrez_Gene_Id) )
rma_expr <- as.matrix(df)

#rma_expr

metadata

rownames(rma_expr) <- counts$Hugo_Symbol
model_m <- model.matrix(~ condition, data = metadata)
batch <- metadata$batch

   sample_name              condition     data_source batch
1  GTEX-ZLWG-1026-SM-4WWC4  healthy       GTEx        1
2  GTEX-13OVJ-2326-SM-5IJGA healthy       GTEx        1
3  GTEX-14BIM-2226-SM-5SI8Y healthy       GTEx        1
4  GTEX-Q734-1626-SM-48U1B  healthy       GTEx        1
5  GTEX-S7SF-0826-SM-4AD4W  healthy       GTEx        1
6  GTEX-12WSD-2826-SM-59HKT healthy       GTEx        2
7  GTEX-145ME-1326-SM-5O98Q healthy       GTEx        2
8  GTEX-S341-1026-SM-4AD71  endometriosis GTEx        2
9  GTEX-P4PP-2026-SM-3P61N  healthy       GTEx        2
10 GTEX-113JC-2226-SM-5EGJG endometriosis GTEx        2

In [53]:
#getting label for output
labels <- counts$Hugo_Symbol
label <- data.frame(labels)

In [60]:
dim(rma_expr[-1])

NULL

In [71]:
#batch correction!
#bc_rma_expr <- ComBat_seq(rma_expr, batch = batch, mod = model_m, ref.batch = 1)



rma_expr <- rma_expr[,colnames(rma_expr)!="Hugo_Symbol"]

rma_expr

bc_rma_expr <- ComBat_seq(rma_expr, batch = batch, group = NULL)

#bc_rma_expr <- ComBat_seq(rma_expr <- rma_expr[,colnames(rma_expr)!="Hugo_Symbol"], batch = batch)

              GTEX-ZLWG-1026-SM-4WWC4 GTEX-13OVJ-2326-SM-5IJGA
FAM208A         2715.29                 2192.72
RADIL            517.00                  914.00
AP1M2              4.00                    2.00
TAF1            2673.00                 3581.00
SIGLEC5            9.49                   18.69
KLF1               1.00                    7.00
USHBP1           334.00                  529.00
LRRC38             2.00                    0.00
NKPD1             10.00                    9.00
SLC26A8            8.00                    8.00
SGCA            1264.00                  479.00
PGF              642.00                  289.00
OR5H14             0.00                    0.00
KLHL1              0.00                    0.00
TUBA3C             1.09                   12.23
UFM1            2299.00                 5104.00
TNPO2           3618.00                 4702.00
NACA2              0.00                    5.00
TMEM256          417.73                  961.97
IFI35            672.00                  739.00
AP001362.1         0.00                    0.00
KLF16            336.12                  142.76
AC026703.1        56.06                   57.99
TCF21            466.45                  370.81
GNL2            1724.00                 2307.00
OR11G2             0.00                    0.00
SLC5A7            26.00                   17.00
OR5A2              0.00                    0.00
MTRNR2L1           0.00                    0.00
SORCS1            92.00                  214.00
⋮             ⋮                       ⋮
NDUFC2.KCTD14     17.02                    8.89
AC104794.4         0.00                    0.00
TEPP              55.00                  188.00
CD151          11295.50                12272.78
CCDC15            42.00                   46.00
PRKCA           1775.00                 1358.00
MAPKAPK3         789.00                  849.00
OXGR1             16.00                   13.00
ZGLP1             77.95                  102.70
ARSD            1118.62                  928.64
AC009403.2        42.00                   39.00
FAM117A         1127.03                  997.03
DUSP14           294.00                   65.00
SCO1             619.00                  549.00
NCOA5           2204.00                 1432.00
SIRT4             28.00                   21.00
CAPZB           6900.00                 9165.00
THEM4            551.00                  376.00
RAB11B          3522.42                 5144.97
C19orf77           6.00                    2.00
DAB2            1644.00                 3589.00
SLC35G1          175.00                  137.00
AL050303.1         0.00                    0.00
NCF2             207.00                  220.00
IFT52            953.00                  666.00
CNGA4             17.00                   15.00
SNRNP35          560.78                  690.47
ALOX12            16.00                    8.06
SNRNP48          676.00                 1340.00
C9orf171           0.00                    1.00
              GTEX-14BIM-2226-SM-5SI8Y GTEX-Q734-1626-SM-48U1B
FAM208A         3086.56                  2888.33
RADIL            884.00                   361.00
AP1M2              2.00                     6.00
TAF1            2568.00                  2741.00
SIGLEC5           11.83                    17.94
KLF1               1.00                     0.00
USHBP1           920.62                   924.00
LRRC38             2.00                     0.00
NKPD1              4.76                    22.40
SLC26A8           12.00                     4.00
SGCA             936.00                  1137.00
PGF              534.00                   252.00
OR5H14             0.00                     0.00
KLHL1              0.00                     0.00
TUBA3C             1.00                     2.00
UFM1            2983.00                  1572.00
TNPO2           3708.00                  3725.00
NACA2              6.00                     0.00
TMEM256          652.42                   539.62
IFI35            489.00                   553.00
AP001362.1        13.58                    18.68
KLF16            110.98                   463.54
AC026703.1       564.36                   282.34
TCF21            539.45                   362.80
GNL2            1348.00                  1085.00
OR11G2             0.00                     0.00
SLC5A7            39.00                    16.00
OR5A2              0.00                     0.00
MTRNR2L1           0.00                     0.00
SORCS1           141.00                   168.00
⋮             ⋮                        ⋮
NDUFC2.KCTD14     20.62                    17.45
AC104794.4         0.00                     0.00
TEPP             174.00                   185.00
CD151           8355.66                  9907.76
CCDC15            55.00                    40.00
PRKCA           1171.00                  2482.00
MAPKAPK3         765.32                   565.00
OXGR1             30.00                    20.00
ZGLP1            176.47                   278.06
ARSD             804.37                   683.83
AC009403.2        47.00                    56.00
FAM117A          979.05                  1831.00
DUSP14           200.00                   275.00
SCO1             521.00                   552.00
NCOA5           2280.00                  2901.00
SIRT4             99.00                   136.00
CAPZB           5719.00                  5066.00
THEM4            698.00                   571.00
RAB11B          2971.72                  4026.69
C19orf77           0.00                     2.00
DAB2            1698.00                  2922.00
SLC35G1          190.00                   102.00
AL050303.1         0.00                     0.00
NCF2             170.00                   157.00
IFT52           1035.00                   627.00
CNGA4              8.00                    13.00
SNRNP35          850.49                   787.08
ALOX12            14.00                    13.07
SNRNP48         1625.00                  1283.00
C9orf171           0.00                     1.00
              GTEX-S7SF-0826-SM-4AD4W GTEX-12WSD-2826-SM-59HKT
FAM208A         2074.97                 3125.08
RADIL            326.00                  708.00
AP1M2             19.00                    4.00
TAF1            1711.85                 3010.35
SIGLEC5           47.18                    3.90
KLF1               0.00                    0.00
USHBP1          1120.00                  730.00
LRRC38             3.00                    0.00
NKPD1              6.32                   10.00
SLC26A8            6.00                    6.00
SGCA             542.00                 1081.00
PGF              422.00                  226.00
OR5H14             2.00                    0.00
KLHL1              0.00                    0.00
TUBA3C             2.00                    2.00
UFM1            1596.00                 2792.00
TNPO2           2841.00                 4464.00
NACA2              5.00                    3.89
TMEM256          483.22                  389.87
IFI35            528.00                  759.00
AP001362.1         5.89                    0.00
KLF16            322.48                  247.14
AC026703.1       201.10                  284.25
TCF21            399.00                  764.43
GNL2             946.00                 1253.00
OR11G2             0.00                    0.00
SLC5A7            13.00                   50.00
OR5A2              0.00                    0.00
MTRNR2L1           0.00                    0.00
SORCS1           107.00                  129.00
⋮             ⋮                       ⋮
NDUFC2.KCTD14      0.00                    8.23
AC104794.4         0.00                    0.00
TEPP              10.00                  226.00
CD151           6356.17                 8779.90
CCDC15            27.00                   66.00
PRKCA           1360.00                 1418.00
MAPKAPK3         505.00                  661.35
OXGR1             27.00                   54.00
ZGLP1             92.78                  177.57
ARSD            1269.76                 1234.46
AC009403.2        29.00                   61.00
FAM117A         1204.04                 1625.97
DUSP14           136.00                  157.00
SCO1             501.00                  478.00
NCOA5           1287.00                 1397.00
SIRT4             49.00                   65.00
CAPZB           5983.00                 5805.00
THEM4            414.00                  685.00
RAB11B          3647.79                 4100.45
C19orf77           3.00                    2.00
DAB2            2637.00                 1624.00
SLC35G1          163.00                  133.00
AL050303.1         0.00                    1.00
NCF2             166.00                   64.00
IFT52            669.00                  992.00
CNGA4             16.00                   25.00
SNRNP35          560.33                  999.94
ALOX12            10.21                   27.22
SNRNP48          596.00                 1282.00
C9orf171           0.00                    0.00
              GTEX-145ME-1326-SM-5O98Q GTEX-S341-1026-SM-4AD71
FAM208A         2388.48                  1791.53
RADIL            235.00                   226.00
AP1M2              5.00                    23.00
TAF1            2272.00                  1632.98
SIGLEC5            9.26                     0.00
KLF1               2.00                     0.00
USHBP1           457.00                   705.00
LRRC38             0.00                    11.00
NKPD1             12.00                     6.00
SLC26A8            2.00                     4.00
SGCA            2106.00                  1430.00
PGF              309.00                   238.00
OR5H14             0.00                     0.00
KLHL1              0.00                     0.00
TUBA3C             1.07                     3.00
UFM1            2001.00                  1502.00
TNPO2           3812.00                  2398.00
NACA2              0.00                     3.00
TMEM256          369.91                   322.58
IFI35            470.00                   528.00
AP001362.1        34.61                     0.00
KLF16            422.39                   648.70
AC026703.1       112.20                   115.96
TCF21            375.57                   371.82
GNL2            1470.00                   930.00
OR11G2             0.00                     0.00
SLC5A7            11.00                     2.00
OR5A2              0.00                     0.00
MTRNR2L1           0.00                     0.00
SORCS1            42.00                    10.00
⋮             ⋮                        ⋮
NDUFC2.KCTD14     11.50                    16.97
AC104794.4         0.00                     0.00
TEPP               8.00                     8.00
CD151          13067.06                 13239.39
CCDC15            15.00                    15.00
PRKCA           2930.00                  2127.00
MAPKAPK3         373.00                   525.00
OXGR1             21.00                    36.00
ZGLP1             55.87                    36.87
ARSD             934.53                   799.00
AC009403.2        40.00                    36.00
FAM117A         1034.12                   977.01
DUSP14           342.00                   311.00
SCO1             597.00                   402.00
NCOA5           1514.00                  1120.00
SIRT4             66.00                    20.00
CAPZB           8692.00                  7246.00
THEM4            508.00                   471.00
RAB11B          3143.46                  2776.58
C19orf77           0.00                     4.00
DAB2            2897.00                  2199.00
SLC35G1          160.00                   175.00
AL050303.1         0.00                     0.00
NCF2              74.00                   153.00
IFT52            972.00                   721.00
CNGA4              3.00                     4.00
SNRNP35          607.50                   480.75
ALOX12            20.74                     7.09
SNRNP48          761.00                   446.00
C9orf171           0.00                     0.00
              GTEX-P4PP-2026-SM-3P61N GTEX-113JC-2226-SM-5EGJG
FAM208A         3661.58                 2231.58
RADIL           1614.00                  811.00
AP1M2             66.00                    3.00
TAF1            5170.20                 2064.30
SIGLEC5            6.37                    9.34
KLF1               0.00                    1.00
USHBP1           528.00                  205.00
LRRC38             2.00                    3.00
NKPD1             23.00                    7.12
SLC26A8            4.00                   17.00
SGCA              84.00                  341.00
PGF               61.00                  141.00
OR5H14             0.00                    0.00
KLHL1              0.00                    1.00
TUBA3C             0.00                    2.00
UFM1            4638.00                 2096.00
TNPO2           8606.14                 3371.00
NACA2              5.28                    0.00
TMEM256          689.36                  324.99
IFI35            701.00                  573.00
AP001362.1         0.00                    4.04
KLF16            318.80                  217.36
AC026703.1       218.76                   91.33
TCF21            101.00                 1034.00
GNL2            1631.00                  924.00
OR11G2             0.00                    0.00
SLC5A7             0.00                  214.00
OR5A2              0.00                    0.00
MTRNR2L1           0.00                    0.00
SORCS1          4321.05                  224.00
⋮             ⋮                       ⋮
NDUFC2.KCTD14     13.48                    6.12
AC104794.4         0.00                    0.00
TEPP             355.00                  150.00
CD151           7951.68                 7133.02
CCDC15           124.00                   55.00
PRKCA           6872.00                 1439.00
MAPKAPK3         971.00                  441.00
OXGR1             12.00                   20.00
ZGLP1            197.64                  101.31
ARSD            3005.35                  675.80
AC009403.2       114.00                   29.00
FAM117A         3268.98                 1123.08
DUSP14           268.00                  163.00
SCO1             741.00                  315.00
NCOA5           3128.00                 1057.00
SIRT4             96.00                   54.00
CAPZB           7772.00                 4842.00
THEM4           1181.00                  373.00
RAB11B          5485.59                 3403.75
C19orf77          11.00                    3.00
DAB2             706.00                 1276.00
SLC35G1          341.00                  135.00
AL050303.1         4.00                    0.00
NCF2              55.00                  100.00
IFT52           1601.00                  702.00
CNGA4             34.00                    8.00
SNRNP35          994.81                  595.49
ALOX12            73.35                   17.14
SNRNP48         1237.00                 1166.00
C9orf171           0.00                    1.00

ERROR: Error in DGEList(counts = counts): The count matrix is a data.frame instead of a matrix and 10 columns are non-numeric.
  Should these columns be gene annotation instead of counts?

In [ ]:
#editing and combining files
final <- data.frame(bc_rma_expr)
final2 <- bind_cols(label,final)

In [ ]:
#writing out
write_tsv(final2,paste0(user_directory,"bc_counts.tsv"))