In [1]:
library(tidyverse)
library(DESeq2)
library(BiocParallel)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.5     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Loading required package: S4Vectors

Loading required package: stats4

Loading required package: BiocGenerics

Loading required package: parallel


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:dplyr’:

    first, rename


The following object is masked from ‘package:tidyr’:

    expand


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice


The following object is masked from ‘package:purrr’:

    reduce


Loading required package: GenomicRanges

Loading required package: GenomeInfoDb

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘matrixStats’


The following object is masked from ‘package:dplyr’:

    count



Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

In [2]:
# Set number of cores to use
n_cores <- detectCores() - 2
BiocParallel::register(MulticoreParam(n_cores))

In [3]:
counts_df <- read_tsv("/mnt/d/gene_expression_example_data/rna_seq_ucec_counts.tsv")
coldata_df <- read_tsv("/mnt/d/gene_expression_example_data/rna_seq_ucec_coldata.tsv")
counts_df <- counts_df %>%
    select(-Entrez_Gene_Id) %>%
    dplyr::rename(symbol = Hugo_Symbol) %>%
    mutate_if(is.numeric, round, 0)
coldata_df <- coldata_df %>%
    mutate(condition = factor(condition, levels = c("healthy", "tumor")))

Rows: 20242 Columns: 248

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr   (1): Hugo_Symbol
dbl (247): Entrez_Gene_Id, GTEX-T6MO-1526-SM-4DM57, GTEX-11P81-1626-SM-5BC52...


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 246 Columns: 3

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (3): sample_name, condition, data_source


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [4]:
min_expr <- 0
min_prop <- 1/3
padj_thresh <- 0.05

In [5]:
filt_counts_df <- counts_df %>%
    filter(rowSums(.[-1] > min_expr) / (ncol(.) - 1) >= min_prop)
filt_expr <- filt_counts_df %>%
    column_to_rownames("symbol") %>%
    as.matrix()

In [6]:
filt_expr

                GTEX-T6MO-1526-SM-4DM57 GTEX-11P81-1626-SM-5BC52
FAM208A         2524                    2703
RADIL            320                     183
AP1M2             34                       8
TAF1            1776                    2509
SIGLEC5            4                      16
KLF1               0                       0
USHBP1           440                     430
LRRC38             0                       4
NKPD1              7                       6
SLC26A8            5                      13
SGCA            1142                     849
PGF              290                     107
TUBA3C             0                       2
UFM1            1746                    2638
TNPO2           2854                    2882
NACA2              6                       4
TMEM256          461                     258
IFI35            433                     286
AP001362.1         0                       0
KLF16            191                     161
AC026703.1       134                      47
TCF21            424                     611
GNL2             892                    1568
SLC5A7             6                      11
SORCS1           135                     112
ELAVL3             3                      13
RAB11FIP4         45                      53
UBR5            4318                    5091
NOTCH2          6846                    6992
LL22NC03-63E9.3    0                       0
⋮               ⋮                       ⋮
CD200             803                    1609
NEB                31                     164
NDUFC2-KCTD14       0                      20
TEPP               19                      24
CD151           10090                   10403
CCDC15             25                      39
PRKCA            2830                    2464
MAPKAPK3          594                     367
OXGR1              14                      28
ZGLP1              59                     117
ARSD              928                    1200
AC009403.2         35                      43
FAM117A           841                    1075
DUSP14            212                     220
SCO1              405                     705
NCOA5            1244                    1734
SIRT4              52                      27
CAPZB            7165                    8779
THEM4             323                     629
RAB11B           3258                    3357
C19orf77            2                       3
DAB2             1891                    3129
SLC35G1           115                     115
NCF2              198                      53
IFT52             795                     791
CNGA4               5                       4
SNRNP35           502                     596
ALOX12              8                      21
SNRNP48           592                    1021
C9orf171            0                       0
                GTEX-13N11-1126-SM-5KM41 GTEX-RTLS-2426-SM-46MUO
FAM208A         2036                     2205
RADIL            209                      577
AP1M2             24                        2
TAF1            1957                     2632
SIGLEC5           31                        6
KLF1               1                        1
USHBP1          1165                      723
LRRC38             6                        0
NKPD1              4                       18
SLC26A8            5                        0
SGCA            1253                      562
PGF              437                      179
TUBA3C             0                        0
UFM1            1803                     2539
TNPO2           3041                     4094
NACA2              0                        4
TMEM256          340                      604
IFI35            787                      503
AP001362.1         0                        0
KLF16            430                      107
AC026703.1       175                       82
TCF21            439                      474
GNL2            1399                      797
SLC5A7             1                       63
SORCS1            29                      274
ELAVL3            20                        5
RAB11FIP4         59                      238
UBR5            4477                     4752
NOTCH2          6533                     4277
LL22NC03-63E9.3    0                        0
⋮               ⋮                        ⋮
CD200            1058                     790
NEB                41                      42
NDUFC2-KCTD14       0                       2
TEPP               20                     454
CD151           12836                    3842
CCDC15             33                      66
PRKCA            1364                    1590
MAPKAPK3          884                     544
OXGR1              17                      18
ZGLP1              55                     113
ARSD              819                     801
AC009403.2         57                      65
FAM117A          1087                    1279
DUSP14            347                      85
SCO1              807                     439
NCOA5            1584                    1388
SIRT4              43                      49
CAPZB            8434                    3691
THEM4             576                     524
RAB11B           4001                    2926
C19orf77            2                       3
DAB2             3231                     822
SLC35G1           212                      92
NCF2              225                      81
IFT52             772                     769
CNGA4              13                      18
SNRNP35           806                     604
ALOX12             10                      16
SNRNP48           610                    1224
C9orf171            0                       0
                GTEX-ZP4G-0726-SM-4WWF2 GTEX-WEY5-0726-SM-4LMID
FAM208A          3770                   2313
RADIL             384                    199
AP1M2              36                     12
TAF1             3631                   2132
SIGLEC5            50                     34
KLF1                0                      1
USHBP1            727                    504
LRRC38              0                      8
NKPD1               9                      5
SLC26A8             7                      1
SGCA             2169                   2400
PGF               454                    505
TUBA3C              3                      0
UFM1             3107                   1910
TNPO2            4307                   3549
NACA2               0                      0
TMEM256           608                    369
IFI35            1121                    524
AP001362.1          0                      0
KLF16             611                    299
AC026703.1         50                     77
TCF21             496                    660
GNL2             2168                   1388
SLC5A7             15                     21
SORCS1             86                    108
ELAVL3              2                      2
RAB11FIP4          71                     58
UBR5             7150                   4303
NOTCH2          11490                   7378
LL22NC03-63E9.3     0                      0
⋮               ⋮                       ⋮
CD200            1280                     561
NEB                77                     186
NDUFC2-KCTD14      13                      14
TEPP               24                      18
CD151           26079                   13348
CCDC15             40                      16
PRKCA            4978                    2718
MAPKAPK3          745                     549
OXGR1              40                      20
ZGLP1              63                      54
ARSD             2435                    1213
AC009403.2         87                      43
FAM117A          1323                    1053
DUSP14            714                     534
SCO1              880                     578
NCOA5            2187                    1455
SIRT4              56                      14
CAPZB           12983                    8149
THEM4             656                     415
RAB11B           5107                    3496
C19orf77            2                       4
DAB2             3284                    1758
SLC35G1           272                     195
NCF2              367                     187
IFT52            1303                     910
CNGA4              15                       5
SNRNP35           931                     596
ALOX12             24                      11
SNRNP48           843                     489
C9orf171            0                       0
                GTEX-T2IS-2226-SM-4DM65 GTEX-PX3G-2026-SM-48U1H
FAM208A         1588                    2703
RADIL            286                     345
AP1M2              7                       9
TAF1            1417                    3048
SIGLEC5            6                       3
KLF1               0                       0
USHBP1           589                     952
LRRC38             8                       2
NKPD1              2                      21
SLC26A8            4                       7
SGCA            1628                    2261
PGF              935                     607
TUBA3C             3                       5
UFM1            1502                    1973
TNPO2           3416                    5908
NACA2              4                       0
TMEM256          479                     382
IFI35            479                     536
AP001362.1         0                       0
KLF16            859                     884
AC026703.1       110                     304
TCF21           1015                     629
GNL2            1328                    1998
SLC5A7            28                      32
SORCS1            60                     118
ELAVL3            14                      21
RAB11FIP4         21                     102
UBR5            2394                    6191
NOTCH2          3919                    8942
LL22NC03-63E9.3    0                       0
⋮               ⋮                       ⋮
CD200           1171                    2009
NEB               20                      38
NDUFC2-KCTD14     10                      10
TEPP              23                      32
CD151           8799                    6580
CCDC15            26                      52
PRKCA            913                    2443
MAPKAPK3         644                    1008
OXGR1             26                      23
ZGLP1            117                     113
ARSD             889                    2086
AC009403.2        47                      57
FAM117A         1056                    3421
DUSP14           255                     552
SCO1             593                     957
NCOA5           1707                    2983
SIRT4             51                     106
CAPZB           6852                    8215
THEM4            600                     836
RAB11B          3383                    6327
C19orf77           1                       5
DAB2            2736                    4356
SLC35G1          196                     236
NCF2              51                     175
IFT52            892                    1171
CNGA4              6                       5
SNRNP35          439                     801
ALOX12            11                      24
SNRNP48          574                     736
C9orf171           1                       0
                GTEX-U3ZN-0726-SM-4DXT5 GTEX-XUW1-0226-SM-4BOOS ⋯
FAM208A         1974                    1861                    ⋯
RADIL            360                     341                    ⋯
AP1M2             33                      10                    ⋯
TAF1            1752                    1866                    ⋯
SIGLEC5            4                       9                    ⋯
KLF1               1                       0                    ⋯
USHBP1           399                     602                    ⋯
LRRC38             2                       0                    ⋯
NKPD1             12                       7                    ⋯
SLC26A8           13                       4                    ⋯
SGCA            1250                     487                    ⋯
PGF              162                     318                    ⋯
TUBA3C             2                       0                    ⋯
UFM1            1540                    1572                    ⋯
TNPO2           2618                    3616                    ⋯
NACA2              0                       0                    ⋯
TMEM256          279                     444                    ⋯
IFI35            443                     430                    ⋯
AP001362.1         0                       0                    ⋯
KLF16            313                     247                    ⋯
AC026703.1       156                     143                    ⋯
TCF21            149                     238                    ⋯
GNL2             965                    1067                    ⋯
SLC5A7             0                       2                    ⋯
SORCS1            70                     173                    ⋯
ELAVL3             3                       2                    ⋯
RAB11FIP4         54                     109                    ⋯
UBR5            3544                    3741                    ⋯
NOTCH2          6316                    3750                    ⋯
LL22NC03-63E9.3    0                       0                    ⋯
⋮               ⋮                       ⋮                       ⋱
CD200           1454                     487                    ⋯
NEB               40                      51                    ⋯
NDUFC2-KCTD14      9                      24                    ⋯
TEPP              16                     126                    ⋯
CD151           8230                    8497                    ⋯
CCDC15            44                      17                    ⋯
PRKCA           3534                    1658                    ⋯
MAPKAPK3         478                     493                    ⋯
OXGR1             11                      22                    ⋯
ZGLP1             69                      70                    ⋯
ARSD            1394                     971                    ⋯
AC009403.2        40                      30                    ⋯
FAM117A         1427                     999                    ⋯
DUSP14           248                     191                    ⋯
SCO1             515                     399                    ⋯
NCOA5           1399                    1516                    ⋯
SIRT4             61                      25                    ⋯
CAPZB           5687                    5235                    ⋯
THEM4            467                     467                    ⋯
RAB11B          3313                    2651                    ⋯
C19orf77           2                       0                    ⋯
DAB2            2527                     779                    ⋯
SLC35G1          185                     109                    ⋯
NCF2              93                      37                    ⋯
IFT52            773                     747                    ⋯
CNGA4             14                      10                    ⋯
SNRNP35          461                     420                    ⋯
ALOX12            16                      10                    ⋯
SNRNP48          449                     458                    ⋯
C9orf171           3                       0                    ⋯
                TCGA-EO-A3AU-01A-21R-A19W-07 TCGA-AJ-A3EK-01A-11R-A19W-07
FAM208A         2437                         3907
RADIL              7                            5
AP1M2           5292                         7638
TAF1            1849                         1886
SIGLEC5           11                           48
KLF1               1                            9
USHBP1            62                           51
LRRC38             1                            0
NKPD1             83                            1
SLC26A8            4                            1
SGCA               6                           40
PGF              125                          221
TUBA3C             0                            0
UFM1            3470                         4982
TNPO2           4282                         5229
NACA2              0                            0
TMEM256         1484                         1496
IFI35           2613                          745
AP001362.1        10                            8
KLF16           1218                          906
AC026703.1       282                           71
TCF21              8                           15
GNL2            4000                         4504
SLC5A7             2                            0
SORCS1            33                           18
ELAVL3             1                            2
RAB11FIP4       2034                         2217
UBR5            4333                         5351
NOTCH2          5322                         5753
LL22NC03-63E9.3   32                            7
⋮               ⋮                            ⋮
CD200             538                          420
NEB                79                           48
NDUFC2-KCTD14       7                           21
TEPP                0                            2
CD151           17485                        15992
CCDC15             99                          173
PRKCA            2436                         4300
MAPKAPK3         1907                         3440
OXGR1             188                            0
ZGLP1              64                          118
ARSD            11537                         8252
AC009403.2         48                          151
FAM117A           506                          823
DUSP14           1544                         1307
SCO1             1227                         1833
NCOA5            2092                         2662
SIRT4              42                           82
CAPZB           13229                        13855
THEM4             385                          635
RAB11B           6000                         5032
C19orf77          290                          109
DAB2              632                         1606
SLC35G1           288                          346
NCF2              682                         1376
IFT52            1363                         1885
CNGA4               9                            6
SNRNP35           781                         1023
ALOX12             10                            6
SNRNP48          1217                          830
C9orf171            0                            1
                TCGA-5S-A9Q8-01A-11R-A40A-07 TCGA-BK-A139-01A-11R-A277-07
FAM208A          836                          7408
RADIL              2                             1
AP1M2           1663                          3209
TAF1             465                          2886
SIGLEC5            2                            94
KLF1               2                            10
USHBP1            28                            64
LRRC38             0                             0
NKPD1             22                            34
SLC26A8            8                            19
SGCA               5                             0
PGF              109                           121
TUBA3C             2                             0
UFM1             922                          4799
TNPO2           1160                          3414
NACA2              2                             0
TMEM256         1063                           456
IFI35            268                           286
AP001362.1        26                             0
KLF16            580                           168
AC026703.1       103                          1111
TCF21             29                             3
GNL2            1248                          3864
SLC5A7             0                             2
SORCS1             1                            68
ELAVL3             0                             0

In [7]:
coldata <- coldata_df %>%
    column_to_rownames("sample_name")

In [8]:
coldata

                             condition data_source
GTEX-T6MO-1526-SM-4DM57      healthy   GTEx
GTEX-11P81-1626-SM-5BC52     healthy   GTEx
GTEX-13N11-1126-SM-5KM41     healthy   GTEx
GTEX-RTLS-2426-SM-46MUO      healthy   GTEx
GTEX-ZP4G-0726-SM-4WWF2      healthy   GTEx
GTEX-WEY5-0726-SM-4LMID      healthy   GTEx
GTEX-T2IS-2226-SM-4DM65      healthy   GTEx
GTEX-PX3G-2026-SM-48U1H      healthy   GTEx
GTEX-U3ZN-0726-SM-4DXT5      healthy   GTEx
GTEX-XUW1-0226-SM-4BOOS      healthy   GTEx
GTEX-PWOO-1526-SM-48TCK      healthy   GTEx
GTEX-Y3IK-2126-SM-4YCDS      healthy   GTEx
GTEX-RU72-2626-SM-4TT75      healthy   GTEx
GTEX-W5WG-1326-SM-4LMI9      healthy   GTEx
GTEX-11GSP-2426-SM-5N9BD     healthy   GTEx
GTEX-QCQG-1326-SM-48U24      healthy   GTEx
GTEX-12ZZX-2126-SM-5LZVL     healthy   GTEx
GTEX-S32W-1426-SM-4AD66      healthy   GTEx
GTEX-PWN1-2026-SM-48TD9      healthy   GTEx
GTEX-13D11-1226-SM-5IFGA     healthy   GTEx
GTEX-ZLWG-1026-SM-4WWC4      healthy   GTEx
GTEX-13OVJ-2326-SM-5IJGA     healthy   GTEx
GTEX-14BIM-2226-SM-5SI8Y     healthy   GTEx
GTEX-Q734-1626-SM-48U1B      healthy   GTEx
GTEX-S7SF-0826-SM-4AD4W      healthy   GTEx
GTEX-12WSD-2826-SM-59HKT     healthy   GTEx
GTEX-145ME-1326-SM-5O98Q     healthy   GTEx
GTEX-S341-1026-SM-4AD71      healthy   GTEx
GTEX-P4PP-2026-SM-3P61N      healthy   GTEx
GTEX-113JC-2226-SM-5EGJG     healthy   GTEx
⋮                            ⋮         ⋮
TCGA-SL-A6JA-01A-11R-A31O-07 tumor     TCGA
TCGA-DI-A1BU-01A-11R-A137-07 tumor     TCGA
TCGA-AX-A3G3-01A-11R-A213-07 tumor     TCGA
TCGA-DI-A2QT-01A-12R-A19W-07 tumor     TCGA
TCGA-AX-A3G4-01A-11R-A213-07 tumor     TCGA
TCGA-AX-A3FZ-01A-11R-A22K-07 tumor     TCGA
TCGA-AJ-A6NU-01A-11R-A34R-07 tumor     TCGA
TCGA-AJ-A5DV-01A-11R-A27V-07 tumor     TCGA
TCGA-EO-A22Y-01A-11R-A180-07 tumor     TCGA
TCGA-EY-A1GX-01A-12R-A13S-07 tumor     TCGA
TCGA-B5-A3FC-01A-11R-A22K-07 tumor     TCGA
TCGA-PG-A914-01A-11R-A37O-07 tumor     TCGA
TCGA-FI-A3PV-01A-11R-A22K-07 tumor     TCGA
TCGA-B5-A0JR-01A-13R-A466-07 tumor     TCGA
TCGA-B5-A5OD-01A-11R-A31O-07 tumor     TCGA
TCGA-AJ-A5DW-01A-11R-A27V-07 tumor     TCGA
TCGA-B5-A3FB-01A-11R-A19W-07 tumor     TCGA
TCGA-PG-A915-01A-11R-A37O-07 tumor     TCGA
TCGA-AX-A3FV-01A-11R-A22K-07 tumor     TCGA
TCGA-KP-A3W0-01A-21R-A22K-07 tumor     TCGA
TCGA-EO-A3AU-01A-21R-A19W-07 tumor     TCGA
TCGA-AJ-A3EK-01A-11R-A19W-07 tumor     TCGA
TCGA-5S-A9Q8-01A-11R-A40A-07 tumor     TCGA
TCGA-BK-A139-01A-11R-A277-07 tumor     TCGA
TCGA-D1-A3DG-01A-11R-A19W-07 tumor     TCGA
TCGA-EO-A22X-01A-11R-A180-07 tumor     TCGA
TCGA-KP-A3W1-01A-11R-A22K-07 tumor     TCGA
TCGA-PG-A916-01A-11R-A37O-07 tumor     TCGA
TCGA-EY-A4KR-01A-11R-A27V-07 tumor     TCGA
TCGA-KP-A3VZ-01A-11R-A22K-07 tumor     TCGA

In [9]:
dds <- DESeqDataSetFromMatrix(
    countData = filt_expr,
    colData = coldata,
    design = ~ condition
)

converting counts to integer mode

In [11]:
dds_seq <- DESeq(dds, parallel = TRUE)
fit_res <- results(
    dds_seq,
    contrast = c("condition", "tumor", "healthy"),
    pAdjustMethod = "BH",
    alpha = padj_thresh,
    parallel = TRUE
)

estimating size factors

estimating dispersions

gene-wise dispersion estimates: 14 workers

mean-dispersion relationship

final dispersion estimates, fitting model and testing: 14 workers

-- replacing outliers and refitting for 1856 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

estimating dispersions

fitting model and testing

In [12]:
dge_res_df <- as_tibble(fit_res, rownames = "symbol")
dge_res_df

      symbol          baseMean     log2FoldChange lfcSE      stat
1     FAM208A         3043.622526  -0.22655764    0.05217910  -4.3419229
2     RADIL            309.665544  -2.24451642    0.17564923 -12.7784020
3     AP1M2           3378.724704   4.21079197    0.25595744  16.4511410
4     TAF1            2244.948024  -0.74801492    0.06089201 -12.2842878
5     SIGLEC5           24.745319   0.59224018    0.20044839   2.9545769
6     KLF1               5.088558   2.74387852    0.21218502  12.9315375
7     USHBP1           452.345308  -2.27625433    0.13681376 -16.6376124
8     LRRC38             5.067697  -0.32169426    0.32802903  -0.9806884
9     NKPD1             32.991438   1.68750453    0.16305123  10.3495360
10    SLC26A8            8.424339   0.19261608    0.17440782   1.1044005
11    SGCA             527.279436  -5.30748808    0.20792253 -25.5262769
12    PGF              392.793012  -0.58502589    0.15344261  -3.8126692
13    TUBA3C             1.760118  -0.42616126    0.42755751  -0.9967344
14    UFM1            2961.002722  -0.12044396    0.05389016  -2.2349897
15    TNPO2           4534.448777  -0.17978810    0.05541781  -3.2442297
16    NACA2              4.306101   0.58884304    0.23116948   2.5472353
17    TMEM256         1274.510105   0.89064917    0.09258538   9.6197604
18    IFI35           1303.621882   0.85858874    0.11993592   7.1587293
19    AP001362.1        17.243720   1.10156731    0.32699612   3.3687473
20    KLF16            901.673677   1.09416228    0.09201950  11.8905479
21    AC026703.1       322.516993  -0.05432829    0.18342068  -0.2961950
22    TCF21            299.182377  -4.27939486    0.23622977 -18.1153919
23    GNL2            2915.798612   0.94208336    0.05178316  18.1928523
24    SLC5A7            15.510657  -3.50581354    0.32586519 -10.7584783
25    SORCS1           135.087556  -2.85669957    0.23103394 -12.3648478
26    ELAVL3             8.155543  -0.60447499    0.26970251  -2.2412657
27    RAB11FIP4       2979.388047   4.12904121    0.16068818  25.6959865
28    UBR5            5192.683050  -0.33492018    0.07949309  -4.2131985
29    NOTCH2          5875.439869  -0.65220095    0.07496070  -8.7005717
30    LL22NC03-63E9.3    5.721515   4.19205842    0.27622598  15.1761917
⋮     ⋮               ⋮            ⋮              ⋮          ⋮
18114 CD200            1169.084033 -0.962669991   0.15097181  -6.3764882
18115 NEB               145.981085  0.689899632   0.18606762   3.7077898
18116 NDUFC2-KCTD14       8.995748  0.032784050   0.31655707   0.1035644
18117 TEPP               56.448332 -3.381033442   0.23076786 -14.6512320
18118 CD151           13519.140251 -0.089715185   0.07758751  -1.1563097
18119 CCDC15             84.416041  0.734255174   0.11329939   6.4806634
18120 PRKCA            1762.579441 -1.742796600   0.13237581 -13.1655212
18121 MAPKAPK3         1615.951284  1.198311836   0.06630704  18.0721670
18122 OXGR1              69.357417  1.493714759   0.19392653   7.7024778
18123 ZGLP1             160.263640  0.309980560   0.13201241   2.3481168
18124 ARSD             3687.143826  1.330074298   0.10301633  12.9112961
18125 AC009403.2         88.229884  0.946395642   0.08954973  10.5683812
18126 FAM117A          1177.067135 -1.053711929   0.08126924 -12.9656912
18127 DUSP14            778.216767  1.244387516   0.09740411  12.7755129
18128 SCO1              952.093095  0.609028255   0.06114539   9.9603294
18129 NCOA5            2510.621654  0.160757130   0.04671186   3.4414630
18130 SIRT4              69.352984 -0.185635752   0.09472469  -1.9597398
18131 CAPZB            9829.895260 -0.005658732   0.05170584  -0.1094409
18132 THEM4             750.570507  0.097014933   0.08133732   1.1927481
18133 RAB11B           5283.388737  0.130585109   0.06947181   1.8796848
18134 C19orf77          244.456607  5.108751304   0.27611885  18.5020009
18135 DAB2             1800.682010 -1.667059495   0.10991229 -15.1671804
18136 SLC35G1           259.266115  0.386390765   0.09041222   4.2736562
18137 NCF2              302.545297  1.118485951   0.14380949   7.7775534
18138 IFT52            1556.647331  0.362130314   0.05583367   6.4858774
18139 CNGA4              41.749094  1.555335916   0.24922491   6.2406920
18140 SNRNP35          1011.493935  0.183631183   0.06321231   2.9049908
18141 ALOX12             21.154092 -0.377534538   0.17777431  -2.1236732
18142 SNRNP48           853.448120 -0.601797432   0.06326031  -9.5130338
18143 C9orf171          171.212355  4.231573585   0.39809462  10.6295673
      pvalue        padj
1      1.412411e-05  1.968457e-05
2      2.164716e-37  7.972888e-37
3      8.230311e-61  5.469690e-60
4      1.100095e-34  3.769410e-34
5      3.130981e-03  3.879090e-03
6      2.987833e-38  1.123487e-37
7      3.721644e-62  2.562496e-61
8      3.267464e-01  3.490027e-01
9      4.205187e-25  1.106201e-24
10     2.694194e-01  2.904728e-01
11    1.007260e-143 3.930048e-142
12     1.374741e-04  1.829794e-04
13     3.188935e-01  3.410365e-01
14     2.541802e-02  2.975797e-02
15     1.177687e-03  1.496063e-03
16     1.085802e-02  1.299882e-02
17     6.598469e-22  1.588378e-21
18     8.142832e-13  1.482245e-12
19     7.551062e-04  9.694234e-04
20     1.325343e-32  4.310809e-32
21     7.670812e-01  7.831931e-01
22     2.409507e-73  2.150304e-72
23     5.879904e-74  5.333955e-73
24     5.405538e-27  1.503260e-26
25     4.049774e-35  1.404608e-34
26     2.500887e-02  2.929218e-02
27    1.296077e-145 5.368657e-144
28     2.517796e-05  3.467727e-05
29     3.302163e-18  7.125493e-18
30     5.084583e-52  2.706854e-51
⋮     ⋮             ⋮
18114 1.811946e-10  3.042775e-10
18115 2.090761e-04  2.759142e-04
18116 9.175150e-01  9.236240e-01
18117 1.322949e-48  6.440103e-48
18118 2.475545e-01  2.679183e-01
18119 9.132022e-11  1.552350e-10
18120 1.385779e-39  5.375710e-39
18121 5.279860e-73  4.650121e-72
18122 1.334529e-14  2.574686e-14
18123 1.886860e-02  2.227426e-02
18124 3.887029e-38  1.456472e-37
18125 4.176412e-26  1.131949e-25
18126 1.914965e-38  7.232141e-38
18127 2.246619e-37  8.271186e-37
18128 2.273084e-23  5.707247e-23
18129 5.785775e-04  7.471268e-04
18130 5.002621e-02  5.736840e-02
18131 9.128528e-01  9.192878e-01
18132 2.329680e-01  2.530527e-01
18133 6.015105e-02  6.860200e-02
18134 1.989489e-76  1.920985e-75
18135 5.832921e-52  3.095252e-51
18136 1.922934e-05  2.661362e-05
18137 7.394056e-15  1.435992e-14
18138 8.821689e-11  1.500299e-10
18139 4.356394e-10  7.207173e-10
18140 3.672639e-03  4.533452e-03
18141 3.369748e-02  3.913040e-02
18142 1.851816e-21  4.402187e-21
18143 2.171174e-26  5.930686e-26